# Numpy mathematical operations

In [3]:
import numpy as np

# 1. Arithmatic operations

Arithmetic operations in NumPy work **element-wise by default** if the arrays are the same shape.
When shapes differ, **NumPy applies broadcasting rules** to align the shapes so that element-wise operations can still occur.

Supported arithmetic operations:

* `+` → Addition
* `-` → Subtraction
* `*` → Multiplication
* `/` → Division
* `//` → Floor Division
* `**` → Exponentiation
* `%` → Modulo

## 2D and 3D Arrays with Axis-Specific Operations

### 2D Array Arithmetic (Matrix Operations)

In [14]:
a = np.array([[1, 2, 3],
              [4, 5, 6]])

b = np.array([[10, 20, 30],
              [40, 50, 60]])

In [15]:
addition = a + b
subtraction = b - a
multiplication = a * b
division = b / a
mod_division = b % a
exponential = b ** a

print(f"Addition:\n", addition)
print(f"subtraction: \n", subtraction)
print(f"multiplication: \n", multiplication)
print(f"division: \n", division)
print(f"mod_division: \n", mod_division)
print(f"exponential: \n", exponential)

Addition:
 [[11 22 33]
 [44 55 66]]
subtraction: 
 [[ 9 18 27]
 [36 45 54]]
multiplication: 
 [[ 10  40  90]
 [160 250 360]]
division: 
 [[10. 10. 10.]
 [10. 10. 10.]]
mod_division: 
 [[0 0 0]
 [0 0 0]]
exponential: 
 [[        10        400      27000]
 [   2560000  312500000 -588640256]]


### **Arithmetic with 1D Array (Broadcasting across a specific axis)**

In [22]:
print(a) # shape: (2, 3)
print() 
c = np.array([1, 2, 3]) # Shape: (3,)

result = a + c
print(result)

[[1 2 3]
 [4 5 6]]

[[2 4 6]
 [5 7 9]]


📌 **Broadcasting Behavior:**

* `c` is broadcasted **across each row** because its size matches the number of columns.
* Operation applies **along axis=1 (columns)**.

| a          | c          | Result     |
| ---------- | ---------- | ---------- |
| \[1, 2, 3] | \[1, 2, 3] | \[2, 4, 6] |
| \[4, 5, 6] | \[1, 2, 3] | \[5, 7, 9] |

In [24]:
print(a) # shape: (2, 3)
print() 
d = np.array([[1], [2]])  # Shape: (2, 1)

result = a + d
print(result)

[[1 2 3]
 [4 5 6]]

[[2 3 4]
 [6 7 8]]


📌 **Broadcasting Behavior:**

* `d` is broadcasted **along each column** because its size matches the number of rows.
* Operation applies **along axis=0 (rows)**.

| a          | d    | Result     |
| ---------- | ---- | ---------- |
| \[1, 2, 3] | \[1] | \[2, 3, 4] |
| \[4, 5, 6] | \[2] | \[6, 7, 8] |

In [30]:
# Broad casting failure case

print(a) # shape: (2, 3)
print() 
d1 = np.array([[1], [2], [3]])

try:
    result = a + d1
except Exception as e:
    print(e)

[[1 2 3]
 [4 5 6]]

operands could not be broadcast together with shapes (2,3) (3,1) 


### **Axis-Wise Scalar Arithmetic**

In [31]:
print(a) # shape: (2, 3)
print() 

result = a + 5
print(result)

[[1 2 3]
 [4 5 6]]

[[ 6  7  8]
 [ 9 10 11]]


👉 Scalar is broadcasted to **all elements.**

## **3D Array Arithmetic (Tensor Operations)**

In [34]:
e = np.array([[[1, 2, 3],
               [4, 5, 6]],
              
              [[7, 8, 9],
               [10, 11, 12]]])

print(e)
print(e.shape)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
(2, 2, 3)


### **Element-wise Arithmetic (Same shape)**

In [36]:
result = e + e
print(result)

[[[ 2  4  6]
  [ 8 10 12]]

 [[14 16 18]
  [20 22 24]]]


### **Arithmetic with 2D Array**

In [39]:
f = np.array([[1, 2, 3],
              [4, 5, 6]]) # Shape: (2, 3)
result = e + f
print(result)

[[[ 2  4  6]
  [ 8 10 12]]

 [[ 8 10 12]
  [14 16 18]]]


📌 **Broadcasting Behavior:**

* `f` is **broadcasted across the first dimension.**
* Effectively, `f` is applied to each "2D slice" of `e` along axis=0.

**Visual:**

* For each `e[i]`, add `f` to it.

In [43]:
# Another 3D broadcasting case
print(e)
print()

f1 = np.array([[[1, 2, 3]]]) # (1, 1, 3)
result = e + f
print(result)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]

[[[ 2  4  6]
  [ 8 10 12]]

 [[ 8 10 12]
  [14 16 18]]]


### **Arithmetic with 1D Array**

In [45]:
g = np.array([1, 2, 3])  # Shape: (3,)

result = e + g
print(result)

[[[ 2  4  6]
  [ 5  7  9]]

 [[ 8 10 12]
  [11 13 15]]]


📌 **Broadcasting Behavior:**

* `g` is broadcasted **along the last dimension (axis=2)**.

**Visual:**

Each 2D slice:

```plaintext
[[1, 2, 3],
 [4, 5, 6]] + [1, 2, 3] => [[2, 4, 6],
                             [5, 7, 9]]
```

### **Arithmetic with Scalar**

In [48]:
print(e + 10)

[[[11 12 13]
  [14 15 16]]

 [[17 18 19]
  [20 21 22]]]


👉 Scalar is **applied to all elements regardless of dimension.**

### **Different Dimension Compatibility**

In [50]:
h = np.array([[100], [200]])  # Shape: (2, 1)

result = e + h
print(result)

[[[101 102 103]
  [204 205 206]]

 [[107 108 109]
  [210 211 212]]]


📌 Broadcasting:

* `h` is broadcasted along axis=2 (size 3).
* Applies to each row of each 2D slice.

#### Visual:

* For e\[0], h = \[\[100], \[200]]
* For e\[1], h = \[\[100], \[200]]

Each row gets the respective addition.

# Summary Table of Axis-wise Arithmetic:

| Operation Example | Operand Shape | Affected Axis    | Broadcasting Effect             |
| ----------------- | ------------- | ---------------- | ------------------------------- |
| 2D + Scalar       | ()            | All              | Scalar applied to all elements  |
| 2D + 1D           | (n,)          | Axis=1 (Columns) | Row-wise addition               |
| 2D + 1D           | (m, 1)        | Axis=0 (Rows)    | Column-wise addition            |
| 3D + 2D           | (m, n)        | Axis=0 (Depth)   | 2D array added to each 2D slice |
| 3D + 1D           | (n,)          | Axis=2           | Added along last dimension      |
| 3D + Scalar       | ()            | All              | Scalar applied to all elements  |

---

# Key Takeaways:

* **Element-wise:** Same shape arrays → direct operation.
* **Broadcasting:** Compatible dimensions → NumPy automatically expands smaller arrays.
* **Axes:** Pay attention to which axis is being broadcasted → it depends on the shapes.
* **Scalar Operations:** Apply to all elements regardless of dimension.


<center><b>Thanks</b></center>