# Numpy mathematical operations

In [7]:
import numpy as np

# 5. Random Number Generation

NumPy’s random functionality is mainly in the **`numpy.random` module** (also available via `np.random`).

**Random Number Generation Categories in NumPy**

We will cover:

1. Pseudorandom Number Generator
2. Uniform Distribution
3. Normal (Gaussian) Distribution
4. Integer Random Generation
5. Random Sampling
6. Other Statistical Distributions
7. Random State / Seed for Reproducibility

## 1. ✅ Pseudorandom Number Generator

NumPy’s random numbers are **not truly random** – they are **pseudorandom** based on an algorithm.

In [8]:
np.random.seed(42)  # Fixes the randomness for reproducibility

* **Important:** When you use the same seed, you get the same sequence of random numbers every time you run the code.

## 2. Uniform Distribution

Generates numbers **evenly distributed over a specified range**.

### Function: `np.random.rand()`

* Range: \[0.0, 1.0)

In [14]:
# 1D array
print(np.random.rand(4))  
# 2D array
print(np.random.rand(2, 3))  
# 3D array
print(np.random.rand(2, 2, 3))

[0.14092422 0.80219698 0.07455064 0.98688694]
[[0.77224477 0.19871568 0.00552212]
 [0.81546143 0.70685734 0.72900717]]
[[[0.77127035 0.07404465 0.35846573]
  [0.11586906 0.86310343 0.62329813]]

 [[0.33089802 0.06355835 0.31098232]
  [0.32518332 0.72960618 0.63755747]]]


## 3. Normal (Gaussian) Distribution

Generates numbers **centered around a mean with specified standard deviation**.

### Function: `np.random.randn()`

* Mean: 0
* Std Dev: 1 (standard normal distribution)


In [18]:
# 1D array
print(np.random.randn(4))
# 2D array
print(np.random.randn(2, 3))
# 3D array
print(np.random.randn(2, 2, 3))

[-0.07201012  1.0035329   0.36163603 -0.64511975]
[[ 0.36139561  1.53803657 -0.03582604]
 [ 1.56464366 -2.6197451   0.8219025 ]]
[[[ 0.08704707 -0.29900735  0.09176078]
  [-1.98756891 -0.21967189  0.35711257]]

 [[ 1.47789404 -0.51827022 -0.8084936 ]
  [-0.50175704  0.91540212  0.32875111]]]


### Custom Normal Distribution:

### Function: `np.random.normal(loc, scale, size)`

* `loc`: mean
* `scale`: standard deviation
* `size`: shape of the output array

In [20]:
# 1D array with mean=5, std=2
print(np.random.normal(5, 2, 4))

[3.94047959 6.02653487 5.1941551  6.93728998]


## 4. Integer Random Generation

### Function: `np.random.randint(low, high, size)`

* Generates random integers **between low (inclusive) and high (exclusive)**.

In [23]:
# 1D array
print(np.random.randint(1, 10, 5))
# 2D array
print(np.random.randint(1, 10, (2, 3)))
# 3D array
print(np.random.randint(1, 10, (2, 2, 3)))

[7 9 7 1 1]
[[9 9 4]
 [9 3 7]]
[[[6 8 9]
  [5 1 3]]

 [[8 6 8]
  [9 4 1]]]


## 5. Random Sampling

### a) `np.random.choice(a, size, replace=True, p=None)`

* Randomly selects elements from an array.
* `replace=False`: Sampling without replacement.

In [26]:
arr = np.array([10, 20, 30, 40, 50])

# Sample 3 elements with replacement
print(np.random.choice(arr, 3))

# Sample 3 elements without replacement
print(np.random.choice(arr, 3, replace=False))

[10 20 40]
[10 50 30]


### b) `np.random.shuffle(x)`

* Shuffles the array **in-place**.

In [28]:
arr = np.array([1, 2, 3, 4, 5])
np.random.shuffle(arr)
print(arr)

[2 5 4 1 3]


### c) `np.random.permutation(x)`

* Returns a **shuffled copy** of the array (original array remains unchanged).

In [30]:
arr = np.array([1, 2, 3, 4, 5])
shuffled = np.random.permutation(arr)
print(shuffled)
print(arr)  # Original array is not changed

[4 2 5 3 1]
[1 2 3 4 5]



## 6. ✅ Other Statistical Distributions

| Function                              | Description                            |
| ------------------------------------- | -------------------------------------- |
| `np.random.uniform(low, high, size)`  | Uniform distribution over \[low, high) |
| `np.random.normal(mean, std, size)`   | Normal distribution                    |
| `np.random.binomial(n, p, size)`      | Binomial distribution                  |
| `np.random.poisson(lam, size)`        | Poisson distribution                   |
| `np.random.beta(a, b, size)`          | Beta distribution                      |
| `np.random.gamma(shape, scale, size)` | Gamma distribution                     |
| `np.random.exponential(scale, size)`  | Exponential distribution               |


In [34]:
# Uniform Distribution with Custom Range
print(np.random.uniform(10, 20, (2, 3)))

[[15.90892943 16.77564362 10.16587829]
 [15.12093058 12.26495775 16.4517279 ]]


In [35]:
# Binomial Distribution
# n=10 trials, p=0.5 probability
print(np.random.binomial(10, 0.5, 5))

[4 6 5 7 3]


In [36]:
# Poisson Distribution
# lam = expected number of events
print(np.random.poisson(3, 5))

[1 6 1 5 4]


## 7. Random State (Seed)

### Why Use Seed?

* Ensures **reproducibility**.
* Same seed → same random numbers each time.

In [61]:
np.random.seed(0)

print(np.random.rand(4))

[0.5488135  0.71518937 0.60276338 0.54488318]


## Complete Summary Table

| Function                              | Purpose                      |
| ------------------------------------- | ---------------------------- |
| `np.random.seed(seed)`                | Set seed for reproducibility |
| `np.random.rand(shape)`               | Uniform distribution \[0, 1) |
| `np.random.randn(shape)`              | Standard normal distribution |
| `np.random.normal(mean, std, size)`   | Normal distribution          |
| `np.random.randint(low, high, size)`  | Random integers              |
| `np.random.choice(a, size, replace)`  | Random sampling              |
| `np.random.shuffle(x)`                | Shuffle array in-place       |
| `np.random.permutation(x)`            | Return shuffled copy         |
| `np.random.uniform(low, high, size)`  | Custom uniform distribution  |
| `np.random.binomial(n, p, size)`      | Binomial distribution        |
| `np.random.poisson(lam, size)`        | Poisson distribution         |
| `np.random.beta(a, b, size)`          | Beta distribution            |
| `np.random.gamma(shape, scale, size)` | Gamma distribution           |
| `np.random.exponential(scale, size)`  | Exponential distribution     |

---

## Key Takeaways:

* Use **uniform, normal, or integers** for general random number needs.
* Use **seed** when you need reproducibility.
* Use **choice, shuffle, permutation** for sampling.
* Use **binomial, poisson, beta, etc.** for statistical simulations.



<center><b>Thanks</b></center>