# Numpy mathematical operations

In [5]:
import numpy as np

# 8. Searching and Sorting

## 1. Searching

We can divide **NumPy searching techniques** into **4 categories:**

1. ✅ Finding indices with conditions
2. ✅ Finding element positions (exact match)
3. ✅ Searching in sorted arrays (binary search)
4. ✅ Useful helper functions (like `np.unique`)


### 1. Searching Based on Conditions

#### 1. **`np.where(condition)`**

* Returns the indices where the condition is **True.**

In [6]:
arr = np.array([10, 20, 30, 40, 50])

# Find indices where elements are greater than 25
indices = np.where(arr > 25)
print(indices)           
print(arr[indices])      

(array([2, 3, 4], dtype=int64),)
[30 40 50]


✅ Works for 1D, 2D, and 3D arrays.

#### 2. **`np.nonzero(arr)`**

* Returns indices of all **non-zero elements.**


In [9]:
arr = np.array([0, 1, 0, 2, 3])
indices = np.nonzero(arr)
print(indices)           
print(arr[indices])      

(array([1, 3, 4], dtype=int64),)
[1 2 3]


✅ Useful for filtering sparse arrays.

#### 3. **`np.argwhere(condition)`**

* Like `np.where` but returns the results as a **coordinate array.**

In [13]:
arr_2d = np.array([[10, 20], [30, 40]])

indices = np.argwhere(arr_2d > 20)
print(indices)

[[1 0]
 [1 1]]


✅ Preferred when working with **multi-dimensional arrays.**

### 2. Finding Exact Match Positions

#### 4. **`np.where(arr == value)`**

* Find indices where **a specific value** exists.

In [17]:
arr = np.array([10, 20, 30, 40, 30])

indices = np.where(arr == 30)
print(indices) 

(array([2, 4], dtype=int64),)


#### 5. **`np.argmax(arr)` and `np.argmin(arr)`**

* Return the **index of the maximum or minimum element.**

In [19]:
arr = np.array([10, 20, 30, 40])

print(np.argmax(arr)) 
print(np.argmin(arr)) 

3
0


✅ You can use `axis` parameter for multi-dimensional arrays.

#### 6. **`np.flatnonzero(arr)`**

* Returns **flattened indices** of non-zero elements.

In [23]:
arr = np.array([[0, 3], [2, 0]])
print(np.flatnonzero(arr))

[1 2]


✅ Efficient when you want 1D positions regardless of original array shape.

### 3. Searching in Sorted Arrays (Fast Binary Search)

#### 7. **`np.searchsorted(arr, values)`**

* Searches for **insertion points** to maintain order in a sorted array.

In [27]:
arr = np.array([10, 20, 30, 40, 50])

# Where would 25 fit to keep array sorted?
index = np.searchsorted(arr, 25)
print(index)

2


✅ Supports binary search (fast searching).

#### 8. **`np.isin(arr, values)`**

* Checks whether each element of the array is in a provided list of values.

In [30]:
arr = np.array([10, 20, 30, 40])
print(np.isin(arr, [20, 40]))  

[False  True False  True]


✅ Element-wise check across the entire array.

### 4 Helper Functions Related to Searching

#### 9. **`np.unique(arr)`**

* Finds **unique elements** in the array.

In [34]:
arr = np.array([10, 20, 10, 30, 20])

print(np.unique(arr))

[10 20 30]


✅ Optional parameters: `return_counts`, `return_index`, `return_inverse`

#### 10. **`np.extract(condition, arr)`**

* Extracts elements from the array where the condition is **True.**

In [37]:
arr = np.array([10, 20, 30, 40, 50])

result = np.extract(arr > 25, arr)
print(result) 

[30 40 50]


✅ Similar to `arr[np.where(condition)]` but sometimes more readable.

## ✅ Summary Table

| Function                     | Purpose                                               |
| ---------------------------- | ----------------------------------------------------- |
| `np.where(condition)`        | Indices where condition is True                       |
| `np.nonzero(arr)`            | Indices of non-zero elements                          |
| `np.argwhere(condition)`     | Multi-dimensional coordinates where condition is True |
| `np.argmax(arr)`             | Index of maximum value                                |
| `np.argmin(arr)`             | Index of minimum value                                |
| `np.flatnonzero(arr)`        | Flat indices of non-zero elements                     |
| `np.searchsorted(arr, v)`    | Insertion index for value in sorted array             |
| `np.isin(arr, values)`       | Check if elements exist in another list               |
| `np.unique(arr)`             | Unique elements in the array                          |
| `np.extract(condition, arr)` | Extract elements matching condition                   |

---

## ✅ Key Notes:

* Use **`where`, `nonzero`, `argwhere`** for condition-based searching.
* Use **`searchsorted`** for sorted arrays (binary search speed).
* Use **`isin`** for membership checking.
* Use **`unique`** and **`extract`** for filtering and deduplication.


## 2. Sorting

**Complete storing methods details available in Manipulation dir and in file 5. sorting arrays**

<center><b>Thanks</b</center>