## 3D and Multi-dimentional arrays

In [1]:
import numpy as np

### Getting familliar with dimentions

#### 0D array (Scalar)

In [25]:
np_0d_arr = np.array(5)
print(f"Type: ", type(np_0d_arr))
print(f"Array: ", np_0d_arr)

print(f"Shape ", np_0d_arr.shape)
print(f"Size: ", np_0d_arr.size)
print(f"Dimensions: ", np_0d_arr.ndim)

Type:  <class 'numpy.ndarray'>
Array:  5
Shape  ()
Size:  1
Dimensions:  0


#### 1D array (Vector)

In [26]:
np_1d_array = np.array(
    [1, 2, 3, 4, 5, 6]
)

print(f"Type: ", type(np_1d_array))
print(f"Array: ", np_1d_array)

print(f"Shape ", np_1d_array.shape)
print(f"Size: ", np_1d_array.size)
print(f"Dimensions: ", np_1d_array.ndim)

Type:  <class 'numpy.ndarray'>
Array:  [1 2 3 4 5 6]
Shape  (6,)
Size:  6
Dimensions:  1


#### 2D array (Matrix)

In [24]:
np_2d_array = np.array(
    [
        [1, 2, 3, 4]
    ]
)

print(np_2d_array)
print(np_2d_array.shape)
print(np_2d_array.size)
print(np_2d_array.ndim)

[[1 2 3 4]]
(1, 4)
4
2


In [27]:
np_2d_array = np.array(
    [
        [1, 2, 3, 4, 5],
        [6, 7, 8, 9, 10]
    ]
)

print(np_2d_array)
print(np_2d_array.shape)
print(np_2d_array.size)
print(np_2d_array.ndim)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
(2, 5)
10
2


In [29]:
np_2d_array = np.array(
    [
        [1, 2, 3, 4, 5],
        [6, 7, 8, 9, 10],
        [11, 22, 33, 44, 55]
    ]
)

print(np_2d_array)
print(np_2d_array.shape)
print(np_2d_array.size)
print(np_2d_array.ndim)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 22 33 44 55]]
(3, 5)
15
2


#### 3D array

In [30]:
np_3d_array = np.array(
    [
        [
            [2, 4, 6],
            [1, 3, 5]
        ]
    ]
)

print(np_3d_array)
print(np_3d_array.shape)
print(np_3d_array.size)
print(np_3d_array.ndim)

[[[2 4 6]
  [1 3 5]]]
(1, 2, 3)
6
3


In [31]:
np_3d_array = np.array(
    [
        [
            [2, 4, 6, 11],
            [1, 3, 5, 11],
            [7, 8, 9, 11]
        ],
        [
            [1, 2, 3, 22],
            [4, 5, 6, 22],
            [12, 34, 56, 22]
        ]
    ]
)

print(np_3d_array)
print(np_3d_array.shape)
print(np_3d_array.size)
print(np_3d_array.ndim)

[[[ 2  4  6 11]
  [ 1  3  5 11]
  [ 7  8  9 11]]

 [[ 1  2  3 22]
  [ 4  5  6 22]
  [12 34 56 22]]]
(2, 3, 4)
24
3


#### 4D Array

In [32]:
np_4d_array = np.array(
    [
        [
            [
                [1, 2, 3, 4]
            ]
        ]
    ]
)

print(np_4d_array)
print(np_4d_array.shape)
print(np_4d_array.size)
print(np_4d_array.ndim)

[[[[1 2 3 4]]]]
(1, 1, 1, 4)
4
4


In [33]:
np_4d_array = np.array(
    [
        [
            [
                [1, 2, 3, 4],
                [5, 6, 7, 8]
            ]
        ]
    ]
)

print(np_4d_array)
print(np_4d_array.shape)
print(np_4d_array.size)
print(np_4d_array.ndim)

[[[[1 2 3 4]
   [5 6 7 8]]]]
(1, 1, 2, 4)
8
4


In [37]:
np_4d_array = np.array(
    [
        [
            [
                [1, 2, 3, 4],
                [5, 6, 7, 8]
            ],
            [
                [11, 22, 33, 44],
                [55, 66, 77, 88]
            ]
        ]
    ]
)

print(np_4d_array)
print(np_4d_array.shape)
print(np_4d_array.size)
print(np_4d_array.ndim)

[[[[ 1  2  3  4]
   [ 5  6  7  8]]

  [[11 22 33 44]
   [55 66 77 88]]]]
(1, 2, 2, 4)
16
4


In [40]:
np_5d_array = np.array(
    [
        [
            [
                [
                    [1, 2, 3, 4, 5]
                ]
            ]
        ]
    ]
)

print(np_5d_array)
print(np_5d_array.shape)
print(np_5d_array.size)
print(np_5d_array.ndim)

[[[[[1 2 3 4 5]]]]]
(1, 1, 1, 1, 5)
5
5


In [47]:
np_5d_array = np.array(
    [
        [
            [
                [
                    [1, 2, 3, 4, 5]
                ],
                [
                    [6, 7, 8, 9, 10]
                ]
            ],
            [
                [
                    [1, 2, 3, 4, 5]
                ],
                [
                    [6, 7, 8, 9, 10]
                ]
            ],
            [
                [
                    [1, 2, 3, 4, 5]
                ],
                [
                    [6, 7, 8, 9, 10]
                ]
            ]
        ]
    ]
)

print(np_5d_array)
print(np_5d_array.shape)
print(np_5d_array.size)
print(np_5d_array.ndim)

[[[[[ 1  2  3  4  5]]

   [[ 6  7  8  9 10]]]


  [[[ 1  2  3  4  5]]

   [[ 6  7  8  9 10]]]


  [[[ 1  2  3  4  5]]

   [[ 6  7  8  9 10]]]]]
(1, 3, 2, 1, 5)
30
5


**Simillarly we can extend this for more dimensions**