# Numpy Data Types

In [1]:
import numpy as np

NumPy provides a rich set of **data types** that are designed for efficient numerical computation. These data types are more specific and memory-efficient compared to Python’s built-in data types.

Here’s a detailed explanation of the **different types of NumPy data types**:

---

## 📌 1. **Numeric Data Types**

These are used to store numbers (integers, floating points, complex numbers).

### a. **Integer Types**

* Used to store whole numbers.
* Variants based on size and sign.

| NumPy Type | Description             | Example Values               |
| ---------- | ----------------------- | ---------------------------- |
| `int8`     | 8-bit signed integer    | -128 to 127                  |
| `int16`    | 16-bit signed integer   | -32,768 to 32,767            |
| `int32`    | 32-bit signed integer   | Large integers               |
| `int64`    | 64-bit signed integer   | Very large integers          |
| `uint8`    | 8-bit unsigned integer  | 0 to 255                     |
| `uint16`   | 16-bit unsigned integer | 0 to 65,535                  |
| `uint32`   | 32-bit unsigned integer | Larger positive integers     |
| `uint64`   | 64-bit unsigned integer | Very large positive integers |

---

### b. **Floating-Point Types**

* Used to store decimal numbers (fractions).
* Variants based on precision.

| NumPy Type | Description            | Example Values                                                 |
| ---------- | ---------------------- | -------------------------------------------------------------- |
| `float16`  | 16-bit floating point  | Approx. 3 decimal places                                       |
| `float32`  | 32-bit floating point  | Approx. 7 decimal places                                       |
| `float64`  | 64-bit floating point  | Approx. 15 decimal places (default)                            |
| `float128` | 128-bit floating point | Extremely high precision (may not be available on all systems) |

---

### c. **Complex Types**

* Used to store complex numbers (real + imaginary parts).

| NumPy Type   | Description                        | Example Values   |
| ------------ | ---------------------------------- | ---------------- |
| `complex64`  | Complex number, two 32-bit floats  | 3 + 4j           |
| `complex128` | Complex number, two 64-bit floats  | 5.2 - 7.8j       |
| `complex256` | Complex number, two 128-bit floats | System dependent |

---

## 📌 2. **Boolean Type**

* Used to store `True` or `False` values.
* **Type:** `bool_`

---

## 📌 3. **String Types**

* Fixed-size Unicode or byte strings.
* Useful for categorical data.

| NumPy Type | Description               |
| ---------- | ------------------------- |
| `string_`  | Fixed-size byte string    |
| `unicode_` | Fixed-size Unicode string |

*Example:*

* `S5` → byte string with max length 5
* `U5` → Unicode string with max length 5

---

## 📌 4. **Object Type**

* **Type:** `object_`
* Can store any Python object (mixed types, lists, dictionaries, etc.).
* Less efficient but flexible.

---

## 📌 5. **Datetime Type**

* Used to store date and time information.
* **Type:** `datetime64`
* Supports time units like seconds (`s`), milliseconds (`ms`), microseconds (`us`), etc.

---

## 📌 6. **Timedelta Type**

* Used to represent time differences.
* **Type:** `timedelta64`
* Example: Duration between two dates.

---

## 📌 7. **Other Less Common Types**

* **Void type (`void`)**: Used for raw data (like in structured arrays).
* **Structured data types**: Like records or tables (similar to database rows).

---

## ✅ Summary Table:

| Category       | Data Types                                               |
| -------------- | -------------------------------------------------------- |
| Numeric        | int8, int16, int32, int64, uint8, uint16, uint32, uint64 |
| Floating Point | float16, float32, float64, float128                      |
| Complex        | complex64, complex128, complex256                        |
| Boolean        | bool\_                                                   |
| String         | string\_, unicode\_                                      |
| Object         | object\_                                                 |
| Date/Time      | datetime64, timedelta64                                  |
| Raw/Structured | void, structured types                                   |

---

Let’s go **one-by-one with detailed explanations and examples for each NumPy data type**.

---

# 📚 Detailed Explanation of NumPy Data Types with Examples

---

## 1️⃣ **Integer Types**

Integers store whole numbers (positive, negative, or zero).

### 👉 Key Types:

* `int8`, `int16`, `int32`, `int64`
* `uint8`, `uint16`, `uint32`, `uint64` (unsigned: only positive)

### ✅ Example:

```python
import numpy as np

a = np.array([1, 2, 3], dtype=np.int8)
print(a, a.dtype)  # [1 2 3] int8

b = np.array([400, 500], dtype=np.int16)
print(b, b.dtype)  # [400 500] int16

c = np.array([10, 20, 30], dtype=np.uint8)
print(c, c.dtype)  # [10 20 30] uint8
```

### 📌 Notes:

* Smaller types use **less memory** but have **smaller range**.
* `uint` types **cannot store negative numbers**.

---

## 2️⃣ **Floating-Point Types**

Used to store decimal (fractional) numbers.

### 👉 Key Types:

* `float16`, `float32`, `float64` (default), `float128`

### ✅ Example:

```python
x = np.array([1.5, 2.7, 3.9], dtype=np.float16)
print(x, x.dtype)  # [1.5 2.7 3.9] float16

y = np.array([4.123456789], dtype=np.float32)
print(y, y.dtype)  # [4.123457] float32  (approx 7 decimal precision)

z = np.array([7.123456789012345], dtype=np.float64)
print(z, z.dtype)  # [7.12345679] float64 (approx 15 decimal precision)
```

### 📌 Notes:

* Larger float types have **higher precision** but use more memory.
* `float64` is the default in NumPy.

---

## 3️⃣ **Complex Types**

Store numbers with a **real and imaginary part**.

### 👉 Key Types:

* `complex64`, `complex128`, `complex256`

### ✅ Example:

```python
p = np.array([1 + 2j, 3 + 4j], dtype=np.complex64)
print(p, p.dtype)  # [1.+2.j 3.+4.j] complex64

q = np.array([5 + 6j], dtype=np.complex128)
print(q, q.dtype)  # [5.+6.j] complex128
```

### 📌 Notes:

* Used in scientific and engineering applications involving complex math.

---

## 4️⃣ **Boolean Type**

Stores `True` or `False` values.

### 👉 Key Type:

* `bool_`

### ✅ Example:

```python
flags = np.array([True, False, True], dtype=np.bool_)
print(flags, flags.dtype)  # [ True False  True] bool
```

### 📌 Notes:

* Useful for masking, filtering, and logical operations.

---

## 5️⃣ **String Types**

Store **fixed-length** byte strings or Unicode strings.

### 👉 Key Types:

* `string_` (bytes)
* `unicode_` (Unicode text)

### ✅ Example:

```python
# Byte string
s = np.array(['apple', 'banana'], dtype='S6')  # Max 6 bytes
print(s, s.dtype)  # [b'apple' b'banana'] |S6

# Unicode string
u = np.array(['cat', 'dog'], dtype='U5')  # Max 5 characters
print(u, u.dtype)  # ['cat' 'dog'] <U5
```

### 📌 Notes:

* Fixed-size → extra space is **padded or truncated.**

---

## 6️⃣ **Object Type**

Stores **arbitrary Python objects.**

### 👉 Key Type:

* `object_`

### ✅ Example:

```python
# Mixed data types
obj_array = np.array([1, 'hello', [2, 3, 4]], dtype=object)
print(obj_array, obj_array.dtype)
```

### 📌 Notes:

* Less memory efficient.
* Can store lists, dictionaries, or mixed types.
* Slower computations compared to native NumPy types.

---

## 7️⃣ **Datetime Type**

Stores **dates and times.**

### 👉 Key Type:

* `datetime64`

### ✅ Example:

```python
dates = np.array(['2025-01-01', '2025-07-04'], dtype='datetime64')
print(dates, dates.dtype)  # ['2025-01-01' '2025-07-04'] datetime64[D]
```

### 📌 Notes:

* Supports **date and time arithmetic.**
* Units like days (`D`), hours (`h`), seconds (`s`) can be specified.

---

## 8️⃣ **Timedelta Type**

Stores **differences between dates and times.**

### 👉 Key Type:

* `timedelta64`

### ✅ Example:

```python
delta = np.array(['2025-07-04'], dtype='datetime64[D]') - np.array(['2025-01-01'], dtype='datetime64[D]')
print(delta, delta.dtype)  # [184] timedelta64[D]
```

### 📌 Notes:

* Useful for **calculating durations** or intervals.

---

## 9️⃣ **Structured and Void Types**

Used for **record-like structures (tables)**.

### 👉 Key Type:

* `void`

### ✅ Example:

```python
person = np.array([(1, 'Alice', 50.5), (2, 'Bob', 60.0)],
                  dtype=[('id', 'i4'), ('name', 'U10'), ('weight', 'f4')])

print(person)
print(person['name'])  # Access specific field
```

### 📌 Notes:

* Works like a **table or database row.**
* Each field can have a different data type.

---

# ✅ Summary:

| Data Type       | Example Usage      |
| --------------- | ------------------ |
| Integer         | Whole numbers      |
| Float           | Decimal numbers    |
| Complex         | Real + imaginary   |
| Boolean         | True/False         |
| String          | Fixed-length text  |
| Object          | Any Python object  |
| Datetime        | Date/Time values   |
| Timedelta       | Time differences   |
| Structured/Void | Table-like records |

---

# Exercise

## int

In [2]:
# Create a NumPy array of type int16 with values from 10 to 50.
arr = np.arange(10, 51, 10, dtype='int16')
print(arr)
print(arr.dtype)

[10 20 30 40 50]
int16


In [3]:
# Creating array with negative values
arr = np.array([-10, -20, -30, -40], dtype='int8')

print(arr)
print(arr.dtype)

[-10 -20 -30 -40]
int8


In [4]:
# Try to create a uint8 array with a negative number and observe the result.
arr = np.array([-10, -20, -30, -40], dtype='uint8')

print(arr)
print(arr.dtype)

[246 236 226 216]
uint8


C:\Users\mahes\AppData\Local\Temp\ipykernel_20820\2488977057.py:2: DeprecationWarning: NumPy will stop allowing conversion of out-of-bound Python integers to integer arrays.  The conversion of -10 to uint8 will fail in the future.
For the old behavior, usually:
    np.array(value).astype(dtype)
will give the desired result (the cast overflows).
  arr = np.array([-10, -20, -30, -40], dtype='uint8')
C:\Users\mahes\AppData\Local\Temp\ipykernel_20820\2488977057.py:2: DeprecationWarning: NumPy will stop allowing conversion of out-of-bound Python integers to integer arrays.  The conversion of -20 to uint8 will fail in the future.
For the old behavior, usually:
    np.array(value).astype(dtype)
will give the desired result (the cast overflows).
  arr = np.array([-10, -20, -30, -40], dtype='uint8')
C:\Users\mahes\AppData\Local\Temp\ipykernel_20820\2488977057.py:2: DeprecationWarning: NumPy will stop allowing conversion of out-of-bound Python integers to integer arrays.  The conversion of -30 t

## Float

In [5]:
# Create a float32 array with whole numbers.

arr = np.array([10, 20], np.float32)
print(arr)
print(arr.dtype)

[10. 20.]
float32


In [6]:
# Create a float32 array with decimal numbers.

arr = np.array([10.5, 20.9], dtype='float32')
print(arr)
print(arr.dtype)

[10.5 20.9]
float32


In [7]:
# Create a float32 array with decimal numbers.

arr = np.array([10.5, 20.9], dtype=np.float32)
print(arr)
print(arr.dtype)

[10.5 20.9]
float32


In [8]:
# Add a number with more than 7 decimals and 
# see how much precision it retains.

arr = np.array([1.23456789], dtype=np.float16)
print(arr)

[1.234]


In [9]:
arr = np.array([1.23456789], dtype=np.float32)
print(arr)

[1.2345679]


In [10]:
arr = np.array([1.23456789], dtype=np.float64)
print(arr)

[1.23456789]


## complex

In [11]:
# Create a complex64 array.
arr = np.array([3 + 4j, 5 + 6j], dtype=np.complex64)
print(arr)
print(arr.dtype)

[3.+4.j 5.+6.j]
complex64


In [12]:
# Extract the real and imaginary parts separately.
print(f"Real: {arr.real}")
print(f"Imaginary: {arr.imag}")

Real: [3. 5.]
Imaginary: [4. 6.]


## bool

In [13]:
# Create a Boolean array using a condition.
arr = np.array([10, 20, 30, 40 ,50])

print(arr)
print(arr.dtype)

[10 20 30 40 50]
int32


In [14]:
cond = arr > 30
print(f"Condition: {cond}")
print(f"Condition type: {cond.dtype}")

print(f"Conditioned elements: {arr[cond]}")

Condition: [False False False  True  True]
Condition type: bool
Conditioned elements: [40 50]


## string

In [15]:
# Create a string array with maximum 4 characters.

arr = np.array(['mahi', 'mani', 'anji', 'man'], dtype='S4')
print(arr)
print(arr.dtype)

[b'mahi' b'mani' b'anji' b'man']
|S4


In [16]:
# Try inserting a string longer than 4 characters and see what happens.
arr = np.insert(arr, 0, "manu")
print(arr)
print(arr.dtype)

arr = np.insert(arr, 0, "manju") # only 4 character considered
print(arr)
print(arr.dtype)

[b'manu' b'mahi' b'mani' b'anji' b'man']
|S4
[b'manj' b'manu' b'mahi' b'mani' b'anji' b'man']
|S4


## object

In [17]:
# Create a NumPy array with mixed data types.
arr = np.array([1, 2, 3.14, "Mahesh"])
print(arr)
print(arr.dtype)

for i in arr:
    print(i.dtype)
    print(type(i))

['1' '2' '3.14' 'Mahesh']
<U32
<U1
<class 'numpy.str_'>
<U1
<class 'numpy.str_'>
<U4
<class 'numpy.str_'>
<U6
<class 'numpy.str_'>


In [18]:
arr = np.array([1, 2, 3.14, "Mahesh"], dtype=np.object_)
print(arr)
print(arr.dtype)

for i in arr:
    print(type(i))

[1 2 3.14 'Mahesh']
object
<class 'int'>
<class 'int'>
<class 'float'>
<class 'str'>


## datetime

In [31]:
# Create a datetime64 array.
arr = np.array(['2003-11-06', '2025-04-07'], dtype=np.datetime64)
print(arr)
print(arr.dtype)

['2003-11-06' '2025-04-07']
datetime64[D]


In [34]:
# Calculate the number of days between two dates.
diff = arr[1] - arr[0]
print(diff)

7823 days


## timedelta

In [38]:
# Timedelta array
delta = np.array([5, 10, 20], dtype='timedelta64[D]')
print(delta)
print(delta.dtype)

[ 5 10 20]
timedelta64[D]


In [39]:
# Add timedelta to datetime
base_date = np.array(['2025-01-01'], dtype='datetime64[D]')
new_dates = base_date + delta
print(new_dates)

['2025-01-06' '2025-01-11' '2025-01-21']


## Structured data types

In [42]:
# Create a structured array with 
# fields: ID (int), Name (string), and Marks (float).

students = np.array([
    (1, "Mahesh", 90),
    (2, "Manju", 99)], 
    dtype=[
    ('ID', 'i4'), ('Name', 'U10'), ('Marks', 'f4')
]
)

print(students)
print(students.dtype)

[(1, 'Mahesh', 90.) (2, 'Manju', 99.)]
[('ID', '<i4'), ('Name', '<U10'), ('Marks', '<f4')]


In [44]:
# student names
print(students['Name'])

['Mahesh' 'Manju']


In [45]:
# student marks
print(students['Marks'])

[90. 99.]


<center><b>Thanks</b><center>