# Vectorization & Broadcasting

## 1. Vectorization

In [3]:
import numpy as np

### What is Vectorization?

**Vectorization** refers to the process of replacing explicit Python loops with **array expressions** to perform operations efficiently.

Instead of processing elements one by one (which is slow in Python), NumPy operations apply directly to entire arrays at once using optimized C code under the hood.

### Why Vectorization is Important?

* Much **faster** than loops.
* Code is **cleaner** and easier to read.
* Takes advantage of **NumPy's optimized** performance.

---

In [4]:
# Without Vectorization (Using Loop)
arr = np.array([1, 2, 3, 4, 5])
result = []

for i in arr:
    result.append(i * 2)

In [5]:
# With Vectorization
arr = np.array([1, 2, 3, 4, 5])
result = arr * 2

print(result)

[ 2  4  6  8 10]


✔️ **No loop needed. Faster and simpler.**

In [7]:
# Other Vectorized Operations
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print(a + b)  
print(a * b)  
print(np.sqrt(a))
print(np.log(a))

[5 7 9]
[ 4 10 18]
[1.         1.41421356 1.73205081]
[0.         0.69314718 1.09861229]


✔️ All these operations are **applied element-wise without loops.**

## 2. Broadcasting

### What is Broadcasting?

**Broadcasting** is a set of rules that NumPy follows to **perform arithmetic operations on arrays of different shapes.**

When shapes don't match, NumPy automatically **expands (broadcasts)** smaller arrays to match the shape of the larger array.

---

### Broadcasting Rules:

When operating on two arrays, NumPy compares their **shapes** starting from the trailing dimensions.

* If the dimensions **are equal or one of them is 1,** they are compatible.
* If the dimensions **are not equal and neither is 1,** NumPy raises an error.

---

In [13]:
# Adding a Scalar to an Array
a = np.array([1, 2, 3])
b = 10

result = a + b
print(result)

[11 12 13]


✔️ Here, `b` (scalar) is **broadcasted** to `[10, 10, 10]`.

In [14]:
# Adding Arrays of Different Shapes
a = np.array([[1, 2, 3],
              [4, 5, 6]])  # Shape: (2, 3)

b = np.array([10, 20, 30])  # Shape: (3,)

result = a + b
print(result)

[[11 22 33]
 [14 25 36]]


✔️ `b` is **broadcasted** to:

```
[[10 20 30]
 [10 20 30]]
```

In [16]:
# Adding Column Vector to Row Vector
a = np.array([[1], [2], [3]])  # Shape: (3, 1)
b = np.array([10, 20, 30])     # Shape: (3,)

result = a + b
print(result)

[[11 21 31]
 [12 22 32]
 [13 23 33]]


✔️ This is **2D Broadcasting**:

* `a` is broadcasted to shape `(3, 3)`
* `b` is broadcasted to shape `(3, 3)`

### Broadcasting Compatibility Example:

| Array A Shape | Array B Shape | Result |
| ------------- | ------------- | ------ |
| (5, 4)        | (4,)          | OK     |
| (3, 1)        | (1, 4)        | OK     |
| (5, 4)        | (3, 4)        | Error  |

In [22]:
# (5, 4) and (4,)
arr1 = np.full(20, 2).reshape(5, 4)
arr2 = np.full(4, 3).reshape(4,)

print(arr1)
print(arr2)
print(arr1.shape)
print(arr2.shape)

[[2 2 2 2]
 [2 2 2 2]
 [2 2 2 2]
 [2 2 2 2]
 [2 2 2 2]]
[3 3 3 3]
(5, 4)
(4,)


In [24]:
sum_ = arr1 + arr2
print(sum_)
print(sum_.shape)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]
(5, 4)


In [25]:
# (3, 1) and (1, 4)
arr1 = np.full(3, 2).reshape(3, 1)
arr2 = np.full(4, 3).reshape(1, 4)

print(arr1)
print(arr2)
print(arr1.shape)
print(arr2.shape)

[[2]
 [2]
 [2]]
[[3 3 3 3]]
(3, 1)
(1, 4)


In [26]:
sum_ = arr1 + arr2
print(sum_)
print(sum_.shape)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]
(3, 4)


In [27]:
# (5, 4) and (3, 4)
arr1 = np.full(20, 2).reshape(5, 4)
arr2 = np.full(12, 3).reshape(3, 4)

print(arr1)
print(arr2)
print(arr1.shape)
print(arr2.shape)

[[2 2 2 2]
 [2 2 2 2]
 [2 2 2 2]
 [2 2 2 2]
 [2 2 2 2]]
[[3 3 3 3]
 [3 3 3 3]
 [3 3 3 3]]
(5, 4)
(3, 4)


In [29]:
try:
    sum_ = arr1 + arr2
except Exception as e:
    print(e)

operands could not be broadcast together with shapes (5,4) (3,4) 


## Summary

| Concept       | Explanation                                       | Example                     |
| ------------- | ------------------------------------------------- | --------------------------- |
| Vectorization | Fast, element-wise array operations without loops | `a * 2`                     |
| Broadcasting  | Automatic shape expansion for array operations    | `a + b` where shapes differ |

---

## Key Benefits:

* 🚀 **Vectorization**: Improves speed, clean code.
* 🚀 **Broadcasting**: Increases flexibility for array operations.

---

# Practice

## Vectorization

In [32]:
# Double the Elements
arr = np.array([5, 10, 15, 20, 25])
print(arr * 2)

[10 20 30 40 50]


In [33]:
# Square of Array Elements
arr = np.array([1, 3, 5, 7, 9])
print(np.square(arr))

[ 1  9 25 49 81]


In [34]:
# Calculate the element-wise sum, difference, and product
a = np.array([2, 4, 6])
b = np.array([1, 3, 5])

sum_ = a + b
diff = a - b
prod = a * b

print(sum_)
print(diff)
print(prod)

[ 3  7 11]
[1 1 1]
[ 2 12 30]


In [35]:
# Find the square root and natural logarithm
arr = np.array([1, 2, 3, 4, 5])

square_root = np.sqrt(arr)
log_ = np.log(arr)

print(f"Square root: {square_root}")
print(f"Log: {log_}")

Square root: [1.         1.41421356 1.73205081 2.         2.23606798]
Log: [0.         0.69314718 1.09861229 1.38629436 1.60943791]


In [56]:
# Without using loops, set all elements greater than 20 to 0.
arr = np.array([10, 15, 20, 25, 30])
arr[arr > 20] = 0
print(arr)

[10 15 20  0  0]


## Broadcasting

In [41]:
# Add 10 to every element using broadcasting.
arr = np.array([[1, 2, 3], [4, 5, 6]])

print(arr + 10)

[[11 12 13]
 [14 15 16]]


In [42]:
# Add b to each row of a using broadcasting.
a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([10, 20, 30])

print(a + b)

[[11 22 33]
 [14 25 36]]


In [43]:
# Add b to each row of a using broadcasting.
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
b = np.array([[100], [200], [300]])
print(a + b)

[[101 102 103]
 [204 205 206]
 [307 308 309]]


In [52]:
# Add b to the last dimension of a using broadcasting.
a = np.ones((3, 3, 3))
b = np.array([1, 2, 3])
print(a)
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]]
[1 2 3]


In [53]:
a[-1] = a[-1] + b
print(a)

[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[2. 3. 4.]
  [2. 3. 4.]
  [2. 3. 4.]]]


In [54]:
# Add a and b using broadcasting and explain the shape of the result.
a = np.array([[1], [2], [3]])
b = np.array([10, 20, 30])

sum_ = a + b # (3, 3)
print(sum_)
print(sum_.shape)

[[11 21 31]
 [12 22 32]
 [13 23 33]]
(3, 3)


<center><b>Thanks</b></center>