# Numpy Array Manipulation

In [1]:
import numpy as np

## 2. Array Joining (Concatenation)

Combine multiple arrays into one.

**Methods:**

* `concatenate()`
* `stack()`
* `hstack()`
* `vstack()`
* `dstack()`
* `column_stack()`
* `row_stack()`
* `append()`

### 1. concatenate()

The `numpy.concatenate()` function is used to **join two or more arrays along an existing axis**.

It is the most general-purpose concatenation function in NumPy and works on arrays of **any dimension**, as long as their shapes match along the other axes.

**Syntax:**

```python
numpy.concatenate((a1, a2, ...), axis=0, out=None, dtype=None, casting="same_kind")
```

**Parameters:**

| Parameter       | Description                                                                                 |
| --------------- | ------------------------------------------------------------------------------------------- |
| **a1, a2, ...** | Sequence of arrays to concatenate (must be the same shape, except along the axis to join).  |
| **axis**        | The axis along which the arrays will be joined. Default is `0`.                             |
| **out**         | Optional. If provided, the result is placed in this array.                                  |
| **dtype**       | Data type of the output array (optional).                                                   |
| **casting**     | Controls what kind of data casting is allowed (usually safe to ignore unless mixing types). |

**Key Rules to Remember:**

1. All arrays **must have the same shape except along the axis specified**.
2. You can concatenate along **any existing axis** (0, 1, 2, etc.).
3. If `axis=None`, the arrays will be flattened before concatenation.


In [2]:
# Basic Concatenation Along Axis 0, 1

a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6]])
c = np.array([[5, 6]]).reshape(2,1)

print(a)
print(a.shape)
print(a.ndim)

print()
print(b)
print(b.shape)
print(b.ndim)

print()
print(c)
print(c.shape)
print(c.ndim)

[[1 2]
 [3 4]]
(2, 2)
2

[[5 6]]
(1, 2)
2

[[5]
 [6]]
(2, 1)
2


✅ Key Rule to Remember:

When using `np.concatenate`:

* All **dimensions must match exactly** except the one you are concatenating along.
* For `axis=1` (columns): number of **rows must be the same.**
* For `axis=0` (rows): number of **columns must be the same.**

- If you are specifying the axis as 0, then 1st index should match,
- if you are specifying the axis as 1, then 0th index should match,

In [3]:
result = np.concatenate((a, b))
print(result)
print(result.shape)

[[1 2]
 [3 4]
 [5 6]]
(3, 2)


In [4]:
result = np.concatenate((a, b), axis=0)
print(result)
print(result.shape)

# Rows will join

[[1 2]
 [3 4]
 [5 6]]
(3, 2)


In [5]:
try:
    result = np.concatenate((a, b), axis = 1)
except Exception as e:
    print(f"Error: {e}")

Error: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 2 and the array at index 1 has size 1


In [6]:
result = np.concatenate((a, c), axis=1)
print(result)
print(result.shape)

# Columns will join

[[1 2 5]
 [3 4 6]]
(2, 3)


In [7]:
# Experimenting when both rows and columns are in same shape

a = np.random.randint(1, 10, (2, 2))
b = np.random.randint(1, 10, (2, 2))

print(a)
print(a.shape)
print(a.ndim)

print()
print(b)
print(b.shape)
print(b.ndim)


[[9 6]
 [3 7]]
(2, 2)
2

[[1 5]
 [9 4]]
(2, 2)
2


In [8]:
result = np.concatenate((a, b), axis=0)
print(result)
print(result.shape)

[[9 6]
 [3 7]
 [1 5]
 [9 4]]
(4, 2)


In [9]:
result = np.concatenate((a, b), axis=1)
print(result)
print(result.shape)

[[9 6 1 5]
 [3 7 9 4]]
(2, 4)


In [10]:
# Concatenating 1D array

a = np.random.randint(1, 10, (3, ))
b = np.random.randint(1, 10, (3, ))

print(a)
print(b)

print(np.concatenate((a, b)))

[8 2 8]
[6 6 4]
[8 2 8 6 6 4]


In [11]:
a = np.random.randint(1, 10, (3, ))
b = np.random.randint(1, 10, (4, ))

print(a)
print(b)

print(np.concatenate((a, b)))

[8 8 5]
[4 4 2 2]
[8 8 5 4 4 2 2]


In [12]:
# Concatenating 3D arrays

a = np.array([[[1, 2]], [[3, 4]]])  # Shape (2, 1, 2)
b = np.array([[[5, 6]]])            # Shape (1, 1, 2)


In [13]:
# For above arrays, if do concatenating with axis 1 or 2 will get error
try:
    print(np.concatenate((a, b), axis=1))
except Exception as e1:
    print(f"Error1: {e1}")
    
try:
    print(np.concatenate((a, b), axis=2))
except Exception as e2:
    print(f"Error2: {e2}")

Error1: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 2 and the array at index 1 has size 1
Error2: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 2 and the array at index 1 has size 1


In [14]:
print(np.concatenate((a, b), axis=0))

[[[1 2]]

 [[3 4]]

 [[5 6]]]


In [15]:
# Flatten and Concatenate Using axis=None
a = np.array([[1, 2], [3, 4]]) # shape (2, 2)
b = np.array([[5, 6]]) # shape (1, 2)

print(np.concatenate((a, b), axis=None))

[1 2 3 4 5 6]


In [16]:
# Concatenating with Different Data Types

a = np.array([1, 2, 3])
b = np.array([4.5, 5.5, 6.5])

print(np.concatenate((a, b)))

# 👉 NumPy automatically upcasts to the more general data type.

[1.  2.  3.  4.5 5.5 6.5]


In [17]:
a = np.array([1, 2, 3])
b = np.array(['a', 'b'])

print(np.concatenate((a, b)))

['1' '2' '3' 'a' 'b']


In [18]:
# Using the out Parameter (Advanced)

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

out_array = np.zeros(6, dtype=int)

print(f"out_array before", out_array)
np.concatenate((a, b), out=out_array)
print(f"out_array before", out_array)

# 👉 The result is stored in the out array directly.

out_array before [0 0 0 0 0 0]
out_array before [1 2 3 4 5 6]


In [19]:
# Shape mismatch error
a = np.array([[1, 2], [3, 4]]) # shape (2, 2)
b = np.array([5, 6, 7]) # shape (3, )

try:
    np.concatenate((a, b), axis=0)
except Exception as e:
    print(e)
    
# Solution: Always ensure arrays have compatible shapes along other axes.

all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)


**Difference Between `concatenate` and `stack`**

| Feature      | `concatenate`                                      | `stack`                    |
| ------------ | -------------------------------------------------- | -------------------------- |
| Axis         | Joins along existing axis                          | Joins along a **new axis** |
| Result Shape | Dimensions remain the same or reduced if flattened | Dimensions increase by 1   |


**When to Use `concatenate()`**

* When you want to **combine arrays along existing axes.**
* When you **don’t need to introduce a new dimension.**
* Useful for data stitching, reshaping, and dataset expansion.


**Key Takeaways:**

* `numpy.concatenate()` is highly flexible and works across all dimensions.
* You must carefully match shapes across all axes **except the axis you are concatenating on.**
* You can flatten arrays using `axis=None`.
* If you want to introduce a **new dimension**, use `numpy.stack()` instead.

### 2. stack()

The `numpy.stack()` function **joins a sequence of arrays along a new axis.**

It is different from `concatenate()`, which joins along an existing axis.

👉 **Key idea:** `stack()` always **increases the number of dimensions by one.**

**Syntax:**

```python
numpy.stack(arrays, axis=0, out=None)
```

**Parameters:**

| Parameter  | Description                                                                        |
| ---------- | ---------------------------------------------------------------------------------- |
| **arrays** | Sequence (list/tuple) of arrays to stack. All arrays must have **the same shape.** |
| **axis**   | The axis along which to stack. Default is `0` (new axis is created at the front).  |
| **out**    | Optional output array to store the result. Usually not required.                   |

**Key Rules:**

* **All input arrays must have the same shape.**
* A **new axis is created** (which increases the dimensionality by one).
* Axis can be positive or negative:

  * Positive → counts from the start (0 is the first axis).
  * Negative → counts from the end (-1 is the last axis).
  
**Why use `stack()` instead of `concatenate()`?**

* `stack()` **adds a new dimension.**
* `concatenate()` **joins along an existing dimension.**

If you need a **higher dimensional array as output**, use `stack()`.

Based on shape, this entire axis thng will work

For 2D array -> shape considered as (ROWS, COLS)

- Positive -> ROWS - 0 & COLS - 1

- Negative -> ROWS - (-2) & COLS - (-1)

In [20]:
a = np.array([1, 2]) # shape: (2, )
b = np.array([3, 4]) # shape: (2, )

result1 = np.stack((a, b), axis = 0)

print(result1)
print(result1.shape)
# 👉 A new axis is created at the front → arrays are stacked vertically.

[[1 2]
 [3 4]]
(2, 2)


In [21]:
result2 = np.stack((a, b), axis = 1)
print(result2)
print(result2.shape)
# 👉 New axis is created at position 1 → arrays are stacked column-wise.

[[1 3]
 [2 4]]
(2, 2)


In [22]:
# Stacking Along Negative Axis
result = np.stack((a, b), axis=-1)
print(result)
print("Shape:", result.shape)

[[1 3]
 [2 4]]
Shape: (2, 2)


In [23]:
result = np.stack((a, b), axis=-2)
print(result)
print("Shape:", result.shape)

[[1 2]
 [3 4]]
Shape: (2, 2)


In [24]:
# Stacking 2D Arrays (Higher Dimensions)
a = np.array([[1, 2], [3, 4]]) # shape (2,2)
b = np.array([[5, 6], [7, 8]]) # shape (2,2)

print(a, end = "\n\n\n")
print(b)

[[1 2]
 [3 4]]


[[5 6]
 [7 8]]


In [25]:
result = np.stack((a, b), axis=0)
print(result)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [26]:
result = np.stack((a, b), axis=1)
print(result)

[[[1 2]
  [5 6]]

 [[3 4]
  [7 8]]]


In [27]:
result = np.stack((a, b), axis=2)
print(result)

[[[1 5]
  [2 6]]

 [[3 7]
  [4 8]]]


In [28]:
# Error When Shapes Don’t Match
a = np.array([1, 2, 3])
b = np.array([4, 5])

try:
    np.stack((a, b))
except Exception as e:
    print(f"Error: {e}")

Error: all input arrays must have the same shape


👉 **Important:** `stack()` requires all input arrays to have the **same shape.**

**Difference Between `stack()`, `concatenate()`, and `vstack()`**

| Feature           | `stack`                            | `concatenate`                                  | `vstack`                        |
| ----------------- | ---------------------------------- | ---------------------------------------------- | ------------------------------- |
| Adds New Axis?    | ✅ Yes                              | ❌ No                                           | ❌ No                            |
| Shape Requirement | All shapes must match              | All shapes must match except along concat axis | Follows vertical stacking rules |
| Typical Usage     | Building higher dimensional arrays | Stitching arrays together along existing axis  | Row-wise stacking               |


**Summary:**

* 🔸 `stack()` **always adds a new axis** → increases dimensionality.
* 🔸 Input arrays must **have exactly the same shape.**
* 🔸 The `axis` parameter controls **where the new axis is inserted.**
* 🔸 `axis=0` → new axis at front → stacks vertically.
* 🔸 `axis=1` → new axis in second position → stacks columns.
* 🔸 **Negative axis values** are supported → count from the end.

### 3. hstack()

The `numpy.hstack()` function is used to **stack arrays in sequence horizontally (along columns)**.
It is a **shortcut for horizontal concatenation** — it stacks arrays side-by-side.

It is conceptually equivalent to `np.concatenate()` with `axis=1` for 2D arrays, and with `axis=0` for 1D arrays.

---

**Syntax:**

```python
numpy.hstack(tup)
```

**Parameters:**

| Parameter | Description                                                                                               |
| --------- | --------------------------------------------------------------------------------------------------------- |
| **tup**   | Tuple or list of arrays to be stacked. Arrays must have the same shape **along all but the second axis**. |

---

**Key Points:**

* For **1D arrays:** `hstack()` simply concatenates them.
* For **2D arrays:** arrays must have the **same number of rows**.
* For **n-dimensional arrays:** arrays must have the same shape except along axis=1.

**Visual Concept:**

If you have:

```text
[1 2]    [3 4]
```

After `hstack`:

```text
[1 2 3 4]
```

In [29]:
# Horizontal Stacking of 1D Arrays

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

result = np.hstack((a, b))
print(result)

# 👉 For 1D arrays, hstack() behaves like simple concatenation.

[1 2 3 4 5 6]


In [30]:
# Horizontal Stacking of 2D Arrays

a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

result = np.hstack((a, b))
print(result)

# 👉 Arrays are stacked side-by-side (columns).

[[1 2 5 6]
 [3 4 7 8]]


In [31]:
# Error Case (Mismatched Rows)

a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6, 7]])

try:
    np.hstack((a, b))
except Exception as e:
    print(f"Error: {e}")

Error: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 2 and the array at index 1 has size 1


In [32]:
# Horizontal Stacking of 3D Arrays

a = np.array([[[1], [2]], [[3], [4]]])  # Shape: (2, 2, 1)
b = np.array([[[5], [6]], [[7], [8]]])  # Shape: (2, 2, 1)

result = np.hstack((a, b))
print(result.shape)
print(result)

(2, 4, 1)
[[[1]
  [2]
  [5]
  [6]]

 [[3]
  [4]
  [7]
  [8]]]


**Difference Between `hstack()` and `concatenate()`**

| Feature           | `hstack()`                                  | `concatenate()`                   |
| ----------------- | ------------------------------------------- | --------------------------------- |
| Axis Used         | Horizontally (axis=1 for 2D, axis=0 for 1D) | Any axis specified by user        |
| Input Requirement | Must match in all but horizontal dimension  | Must match in all but concat axis |

👉 `hstack()` is **simpler** when you want horizontal stacking without specifying axis.

---

**Difference Between `hstack()`, `vstack()`, and `stack()`**

| Method     | Stacking Type             | Adds New Axis? |
| ---------- | ------------------------- | -------------- |
| `hstack()` | Horizontal (side-by-side) | No             |
| `vstack()` | Vertical (top-to-bottom)  | No             |
| `stack()`  | Adds a New Axis           | Yes            |

---

**Summary:**

* ✅ `hstack()` **stacks arrays side-by-side (column-wise).**
* ✅ Works like `concatenate()` with `axis=1` for 2D arrays.
* ✅ Arrays must have **the same shape except along the horizontal dimension.**
* ✅ Very useful for quickly building datasets or side-by-side layouts.


### 4. vstack()

The `numpy.vstack()` function **stacks arrays vertically (row-wise)**.

* It **joins arrays along axis 0** (adds them one below the other).
* For **1D arrays**, it converts them to 2D rows before stacking.

It is a **convenient shortcut** for vertical stacking, similar to using:

```python
np.concatenate((a, b), axis=0)
```

for 2D arrays.

---

**Syntax:**

```python
numpy.vstack(tup)
```

**Parameters:**

| Parameter | Description                                         |
| --------- | --------------------------------------------------- |
| **tup**   | A tuple or list of arrays to be stacked vertically. |

---

**Key Points:**

* Arrays must have the **same number of columns** (or length for 1D arrays).
* For **1D arrays**, they are treated as rows and promoted to 2D automatically.
* **No new axis is created** (unlike `stack()`).

---

**Visual Concept:**

If you have:

```text
[1 2]  stacked with  [3 4]  using vstack →
```

Result:

```text
[[1 2]
 [3 4]]
```


In [33]:
# Vertical Stacking of 1D Arrays

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

result = np.vstack((a, b))
print(result)
print("Shape:", result.shape)

[[1 2 3]
 [4 5 6]]
Shape: (2, 3)


In [34]:
# Vertical Stacking of 2D Arrays
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6]])

result = np.vstack((a, b))
print(result)
print("Shape:", result.shape)

[[1 2]
 [3 4]
 [5 6]]
Shape: (3, 2)


In [35]:
# Error When Columns Don’t Match

a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6, 7]])

try:
    np.vstack((a, b))
except Exception as e:
    print(f"Error: {e}")

Error: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 2 and the array at index 1 has size 3


In [36]:
# Working with 3D Arrays
a = np.array([[[1, 2]], [[3, 4]]])  # Shape: (2, 1, 2)
b = np.array([[[5, 6]]])            # Shape: (1, 1, 2)

result = np.vstack((a, b))
print(result.shape)
print(result)


(3, 1, 2)
[[[1 2]]

 [[3 4]]

 [[5 6]]]


**Difference Between `vstack()` and `hstack()`**

| Feature               | `vstack()`                 | `hstack()`                  |
| --------------------- | -------------------------- | --------------------------- |
| Stacking Direction    | Vertically (top to bottom) | Horizontally (side-by-side) |
| Dimension Requirement | Same number of columns     | Same number of rows         |
| Axis Affected         | Stacks along axis=0        | Stacks along axis=1         |

---

**Difference Between `vstack()`, `hstack()`, and `stack()`**

| Method     | Stacking Type             | Adds New Axis? |
| ---------- | ------------------------- | -------------- |
| `vstack()` | Vertical (top-to-bottom)  | No             |
| `hstack()` | Horizontal (side-by-side) | No             |
| `stack()`  | Adds a New Axis           | Yes            |

---

**Summary:**

* ✅ `vstack()` stacks arrays vertically (row-wise).
* ✅ For 1D arrays, they are **converted to rows automatically.**
* ✅ Arrays must have the **same number of columns.**
* ✅ It is equivalent to `concatenate` with `axis=0` for 2D arrays.


### 5. dstack()

The `numpy.dstack()` function is used to **stack arrays in sequence along the third axis (axis=2), also known as "depth-wise" stacking.**

It is most useful when working with **multi-dimensional arrays (especially 2D arrays)** where you want to combine arrays into a single array with an additional depth layer.

Think of **"depth" as stacking layers like a sandwich.**

---

**Syntax:**

```python
numpy.dstack(tup)
```

**Parameters:**

| Parameter | Description                                                              |
| --------- | ------------------------------------------------------------------------ |
| **tup**   | A sequence (tuple or list) of arrays to be stacked along depth (axis=2). |

---

**Key Rules:**

* Arrays **must have the same shape** along all axes **except axis=2.**
* For **1D arrays:** NumPy first promotes them to shape `(n, 1)` before stacking.
* For **2D arrays:** The depth is introduced as a third axis.

---

**Visual Explanation:**

Suppose you have:

```text
Array 1: [1 2]     Array 2: [3 4]
```

After `dstack`:

```text
Result: [[[1 3]]
         [[2 4]]]
```

👉 It stacks arrays **layer by layer along depth (axis=2).**


In [37]:
# Stacking 1D Arrays

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

result = np.dstack((a, b))
print(result)
print(f"Shape: {result.shape}")
print(f"Dim: {result.ndim}")

[[[1 4]
  [2 5]
  [3 6]]]
Shape: (1, 3, 2)
Dim: 3


In [38]:
# Stacking 2D Arrays

a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

result = np.dstack((a, b))
print(result)
print(f"Shape: {result.shape}")
print(f"Dim: {result.ndim}")

[[[1 5]
  [2 6]]

 [[3 7]
  [4 8]]]
Shape: (2, 2, 2)
Dim: 3


In [39]:
# Stacking 3D Arrays

a = np.array([[[1, 2]], [[3, 4]]])  # Shape: (2, 1, 2)
b = np.array([[[5, 6]], [[7, 8]]])  # Shape: (2, 1, 2)

result = np.dstack((a, b))
print(result)
print(f"Shape: {result.shape}")
print(f"Dim: {result.ndim}")

[[[1 2 5 6]]

 [[3 4 7 8]]]
Shape: (2, 1, 4)
Dim: 3


In [40]:
# Error Case When Shapes Don’t Match

a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6, 7], [8, 9, 10]])

try:
    np.dstack((a, b))
except Exception as e:
    print(f"Error: {e}")

Error: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 2 and the array at index 1 has size 3


**Difference Between `dstack()`, `hstack()`, and `vstack()`**

| Method     | Stacking Direction          | Axis Affected | Shape Requirement               |
| ---------- | --------------------------- | ------------- | ------------------------------- |
| `vstack()` | Vertical (top to bottom)    | axis=0        | Same number of columns          |
| `hstack()` | Horizontal (side by side)   | axis=1        | Same number of rows             |
| `dstack()` | Depth-wise (layer by layer) | axis=2        | Same shape for rows and columns |

---

**Difference Between `dstack()` and `stack()`**

| Feature         | `dstack()`                           | `stack()`                  |
| --------------- | ------------------------------------ | -------------------------- |
| Axis Used       | Always stacks along axis=2           | User can choose any axis   |
| New Axis Added? | Yes, at depth layer                  | Yes, at specified position |
| Simplicity      | Simpler, specific for depth stacking | More flexible              |

---

**Summary:**

* ✅ `numpy.dstack()` stacks arrays **along the third axis (axis=2)** → depth-wise stacking.
* ✅ For **1D arrays**, NumPy promotes them to 2D before stacking.
* ✅ All arrays must have **the same shape except along depth.**
* ✅ Best for **creating multi-layered structures** like image channels or depth maps.


### 6. column_stack()

The `numpy.column_stack()` function **stacks 1D arrays as columns into a 2D array.**

It is useful when you want to **combine multiple 1D arrays into a multi-column matrix.**

It automatically:

* Promotes **1D arrays to columns**.
* Leaves **2D arrays unchanged.**

---

**Syntax:**

```python
numpy.column_stack(tup)
```

**Parameters:**

| Parameter | Description                                             |
| --------- | ------------------------------------------------------- |
| **tup**   | A tuple or list of 1D or 2D arrays to stack as columns. |

---

**Key Rules:**

* **1D arrays are treated as column vectors.**
* Arrays must have **the same number of elements** (same length).
* The result is **always a 2D array**.

---

**Visual Concept:**

Suppose you have:

```text
a = [1, 2, 3]   →  becomes  [[1]
                              [2]
                              [3]]
b = [4, 5, 6]   →  becomes  [[4]
                              [5]
                              [6]]
```

After `column_stack((a, b))`:

```text
[[1 4]
 [2 5]
 [3 6]]
```


In [41]:
# Stacking 1D Arrays as Columns
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

result = np.column_stack((a, b))
print(result)

# 👉 a and b are converted to columns and stacked side by side.

[[1 4]
 [2 5]
 [3 6]]


In [42]:
# Stacking 2D Arrays
a = np.array([[1], [2], [3]])
b = np.array([[4], [5], [6]])

result = np.column_stack((a, b))
print(result)

# 👉 Since arrays are already 2D, they are just horizontally stacked.

[[1 4]
 [2 5]
 [3 6]]


In [43]:
# Stacking Mixture of 1D and 2D Arrays
a = np.array([1, 2, 3])              # 1D array
b = np.array([[4], [5], [6]])        # 2D array

result = np.column_stack((a, b))
print(result)

[[1 4]
 [2 5]
 [3 6]]


In [44]:
# Error Case (Length Mismatch)
a = np.array([1, 2, 3])
b = np.array([4, 5])

try:
    np.column_stack((a, b))
except Exception as e:
    print(f"Error: {e}")

Error: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 3 and the array at index 1 has size 2


**Difference Between `column_stack()` and `hstack()`**

| Feature            | `column_stack()`                              | `hstack()`                                            |
| ------------------ | --------------------------------------------- | ----------------------------------------------------- |
| 1D Arrays Handling | Converts to column vectors                    | Concatenates side by side (remains 1D if input is 1D) |
| Result Shape       | Always 2D                                     | Can be 1D or 2D                                       |
| Typical Usage      | Building multi-column matrices from 1D arrays | General horizontal stacking                           |

👉 **Key Point:**

* `column_stack()` → **Always 2D** result.
* `hstack()` → Result can be **1D if input is 1D.**

**Summary:**

* ✅ `numpy.column_stack()` stacks **1D arrays as columns into a 2D array.**
* ✅ It always returns **a 2D result** (no matter the input).
* ✅ Useful for building matrices where **each input array is a separate feature (column).**
* ✅ For 2D arrays → behaves like `hstack`.

### 7. row_stack()

The `numpy.row_stack()` function **stacks arrays in sequence vertically (along rows, axis=0).**
It is **almost identical to `numpy.vstack()`** — in fact, **`numpy.row_stack()` is just an alias for `numpy.vstack()`.**

---

**Syntax:**

```python
numpy.row_stack(tup)
```

**Parameters:**

| Parameter | Description                                                    |
| --------- | -------------------------------------------------------------- |
| **tup**   | A sequence (tuple or list) of arrays to be stacked vertically. |

---

**Key Rules:**

* **1D arrays are treated as rows.**
* All input arrays must have the **same number of columns** (or length for 1D arrays).
* The result is **always at least 2D.**
* Behaves like `vstack()` → stacks vertically (top to bottom).

---

**Visual Concept:**

If you have:

```text
a = [1, 2, 3] → promoted to [[1 2 3]]
b = [4, 5, 6] → promoted to [[4 5 6]]
```

Result:

```text
[[1 2 3]
 [4 5 6]]
```

👉 **The arrays become rows in the final 2D array.**


In [45]:
# Stacking 1D Arrays

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

result = np.row_stack((a, b))
print(result)

[[1 2 3]
 [4 5 6]]


In [46]:
# Stacking 2D Arrays

a = np.array([[1, 2]])
b = np.array([[3, 4]])

result = np.row_stack((a, b))
print(result)

[[1 2]
 [3 4]]


In [47]:
# Stacking Mixture of 1D and 2D Arrays

a = np.array([1, 2, 3])
b = np.array([[4, 5, 6]])

result = np.row_stack((a, b))
print(result)

[[1 2 3]
 [4 5 6]]


In [48]:
# Error Case When Columns Don’t Match

a = np.array([1, 2, 3])
b = np.array([4, 5])

try:
    np.row_stack((a, b))
except Exception as e:
    print(f"Error: {e}")

Error: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 3 and the array at index 1 has size 2


**Difference Between `row_stack()`, `vstack()`, and `hstack()`**

| Feature            | `row_stack()`            | `vstack()`               | `hstack()`                  |
| ------------------ | ------------------------ | ------------------------ | --------------------------- |
| Stacking Direction | Vertical (top to bottom) | Vertical (top to bottom) | Horizontal (side by side)   |
| 1D Arrays Handling | Treated as rows          | Treated as rows          | Concatenated as 1D          |
| Result Shape       | Always 2D                | Always 2D                | 1D or 2D depending on input |

👉 **Important:**
`row_stack()` and `vstack()` behave **identically.**

The only difference is **the name.**

---

**Difference Between `row_stack()` and `column_stack()`**

| Feature            | `row_stack()`            | `column_stack()`          |
| ------------------ | ------------------------ | ------------------------- |
| Stacking Direction | Vertical (top to bottom) | Horizontal (side by side) |
| 1D Arrays Handling | Treated as rows          | Treated as columns        |
| Result Shape       | Always 2D                | Always 2D                 |

---

**Summary:**

* ✅ `numpy.row_stack()` **stacks arrays vertically** (row-wise, along axis=0).
* ✅ 1D arrays are **converted to rows automatically.**
* ✅ Behaves **exactly like `numpy.vstack()`.**
* ✅ Useful for **building multi-row arrays from 1D inputs.**
* ✅ Arrays must have the **same number of columns (or length).**

---

### 8. append()

The `numpy.append()` function is used to **add (append) elements to the end of an array.**

It **does not modify the original array** — it always returns a **new array**.

👉 `numpy.append()` is more **flexible** than stacking functions because:

* You can append **individual elements**.
* You can append **arrays of any shape** (but you need to be careful about axis handling).

---

**Syntax:**

```python
numpy.append(arr, values, axis=None)
```

**Parameters:**

| Parameter  | Description                                                                           |
| ---------- | ------------------------------------------------------------------------------------- |
| **arr**    | The input array.                                                                      |
| **values** | Values to be appended to `arr`. Can be a single element or an array.                  |
| **axis**   | The axis along which to append. If `None` (default), both arrays are flattened first. |

---

**Key Rules:**

* If `axis=None` (default), the **arrays are flattened (converted to 1D)** before appending.
* If `axis` is specified:

  * The arrays must have **matching dimensions** along all axes except the one specified.
* `numpy.append()` always **creates a new array** (it is not an in-place operation).


In [49]:
# Append Without Axis (Default Behavior)
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

result = np.append(a, b)
print(result)

[1 2 3 4 5 6]


In [50]:
# Append a Scalar
a = np.array([1, 2, 3])

result = np.append(a, 4)
print(result)


[1 2 3 4]


In [51]:
# Append Along Axis = 0

a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6]])

result = np.append(a, b, axis=0)
print(result)

[[1 2]
 [3 4]
 [5 6]]


👉 **Explanation:**

* Arrays are stacked **vertically (row-wise).**
* The number of **columns must match.**

In [52]:
# Append Along Axis = 1

a = np.array([[1, 2], [3, 4]])
b = np.array([[5], [6]])

result = np.append(a, b, axis=1)
print(result)


[[1 2 5]
 [3 4 6]]


👉 **Explanation:**

* Arrays are stacked **horizontally (column-wise).**
* The number of **rows must match.**

In [53]:
# Error When Shape Does Not Match
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6, 7]])

try:
    np.append((a, b), axis=0)
except Exception as e:
    print(f"Error: {e}")

Error: append() missing 1 required positional argument: 'values'


In [ ]:
# Append Multidimensional Arrays Without Axis (Flattening)
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6]])

result = np.append(a, b)
print(result)

[1 2 3 4 5 6]


**Difference Between `numpy.append()` and Stacking Functions**

| Feature             | `numpy.append()`           | `vstack()`, `hstack()`, `dstack()`      |
| ------------------- | -------------------------- | --------------------------------------- |
| Can Flatten Input?  | ✅ Yes (if axis=None)       | ❌ No, follows array dimensions strictly |
| Accepts Scalars?    | ✅ Yes                      | ❌ No, must be arrays                    |
| Supports Axis?      | ✅ Yes                      | ✅ Yes                                   |
| Returns New Array?  | ✅ Always creates new array | ✅ Always creates new array              |
| In-place Operation? | ❌ No                       | ❌ No                                    |
| Flexible on Shape?  | ✅ Yes when axis=None       | ❌ Strict shape matching required        |

---

**Summary:**

* ✅ `numpy.append()` is used to **add elements or arrays to the end of another array.**
* ✅ By default (`axis=None`), **arrays are flattened** before appending.
* ✅ When using an `axis`, shapes must match along all other axes.
* ✅ It is **not an in-place operation** → always returns a new array.
* ✅ It can **append scalars, 1D arrays, or multi-dimensional arrays.**
* ✅ It is **more flexible** but less efficient than stacking functions in some use cases.


**comprehensive consolidation of all NumPy array joining (concatenation) methods**, including purpose, behavior, input requirements, axis handling, return type, and key differences. This will serve as your **go-to reference** for all array joining techniques in NumPy.

---

# ✅ NumPy Array Joining Methods – Consolidated Reference

| Function                         | Joins Along    | Handles 1D Arrays | Promotes Dim? | Result Dim | Axis Param? | Auto Flatten (if axis=None)? | Use Case Example                 |
| -------------------------------- | -------------- | ----------------- | ------------- | ---------- | ----------- | ---------------------------- | -------------------------------- |
| `np.concatenate()`               | Custom Axis    | No                | No            | Depends    | ✅ Yes       | ❌ No                         | Join arrays along specific axis  |
| `np.stack()`                     | New Axis       | No                | No            | +1 Dim     | ✅ Yes       | ❌ No                         | Stack as layers (adds new axis)  |
| `np.hstack()`                    | Horizontal     | ✅ Yes             | ✅ Yes         | 1D or 2D   | ❌ No        | ❌ No                         | Join side-by-side (columns)      |
| `np.vstack()` / `np.row_stack()` | Vertical       | ✅ Yes             | ✅ Yes         | 2D         | ❌ No        | ❌ No                         | Stack top-to-bottom (rows)       |
| `np.column_stack()`              | Columns        | ✅ Yes             | ✅ Yes         | 2D         | ❌ No        | ❌ No                         | Turn 1D arrays into columns      |
| `np.dstack()`                    | Depth (axis=2) | ✅ Yes             | ✅ Yes         | 3D         | ❌ No        | ❌ No                         | Stack as third axis (layers)     |
| `np.append()`                    | Custom Axis    | ✅ Yes             | ✅ Yes         | Varies     | ✅ Yes       | ✅ Yes                        | Append values or arrays flexibly |

---

## 📌 Detailed Highlights

### 1. ✅ `np.concatenate()`

* 🔧 Flexible joining along any axis.
* 🔺 Arrays must **match in shape** except along the join axis.
* ❌ Cannot join 1D and 2D arrays together directly.

```python
np.concatenate((a, b), axis=0)
```

---

### 2. ✅ `np.stack()`

* ➕ Adds a **new axis** for stacking.
* All arrays must have **same shape**.

```python
np.stack((a, b), axis=0)  # adds new dimension
```

---

### 3. ✅ `np.hstack()`

* 🤝 Stacks arrays **horizontally (columns)**.
* For 1D → concatenates.
* For 2D → stacks along `axis=1`.

```python
np.hstack((a, b))
```

---

### 4. ✅ `np.vstack()` / `np.row_stack()`

* ⬇️ Stacks arrays **vertically (rows)**.
* For 1D → promotes to row vector.
* Result is always **2D**.

```python
np.vstack((a, b))  # or np.row_stack((a, b))
```

---

### 5. ✅ `np.column_stack()`

* 📊 Stacks **1D arrays as columns** in a 2D array.
* For 2D → behaves like `hstack`.

```python
np.column_stack((a, b))
```

---

### 6. ✅ `np.dstack()`

* 🧱 Stacks arrays **along depth (axis=2)**.
* For 1D → promotes to shape `(n, 1)`.
* Result is always **3D**.

```python
np.dstack((a, b))
```

---

### 7. ✅ `np.append()`

* 🧩 Appends arrays or values to existing arrays.
* If `axis=None` (default) → **flattens** before appending.
* ✅ Supports appending scalars or arrays.

```python
np.append(a, b)               # flattens
np.append(a, b, axis=0)       # requires shape match
```

---

## 🧠 Quick Decision Table

| Task                              | Best Function               |
| --------------------------------- | --------------------------- |
| Concatenate along specific axis   | `concatenate()`             |
| Add a new axis while joining      | `stack()`                   |
| Join 1D arrays side-by-side       | `column_stack()`            |
| Join 1D arrays as rows            | `row_stack()` or `vstack()` |
| Stack 2D arrays as layers         | `dstack()`                  |
| Append scalars or arrays flexibly | `append()`                  |
| Horizontally join 2D arrays       | `hstack()`                  |
| Vertically join 2D arrays         | `vstack()`                  |

---

## ✅ Summary Cheat Sheet (Shape Behavior)

| Function         | Input Shape Example | Resulting Shape     |
| ---------------- | ------------------- | ------------------- |
| `append()`       | (2,), (3,)          | (5,) if axis=None   |
| `concatenate()`  | (2, 3), (1, 3)      | (3, 3) if axis=0    |
| `stack()`        | (2, 3), (2, 3)      | (2, 2, 3) if axis=0 |
| `vstack()`       | (3,), (3,)          | (2, 3)              |
| `hstack()`       | (3,), (3,)          | (6,)                |
| `column_stack()` | (3,), (3,)          | (3, 2)              |
| `dstack()`       | (3,), (3,)          | (3, 1, 2)           |

---


<center><b>Thanks</b></center>