# Numpy Array Manipulation

In [1]:
import numpy as np

## 3. Array splitting

Break an array into multiple smaller arrays.

**Methods:**

- array_split()

- split()

- hsplit()

- vsplit()

- dsplit()

### 1. array_split()

`numpy.array_split()` is a method that **splits an array into sub-arrays.**

✅ It allows splitting **even when the array size is not divisible evenly.**

✅ It can split **along any axis.**

---

**Syntax:**

```python
numpy.array_split(array, sections, axis=0)
```

**Parameters:**

* **array**: The input array you want to split.
* **sections**: Number of parts to split into.
* **axis**: The axis along which to split. Default is `axis=0` (rows).

---

**Key Features:**

* ✔️ It **allows uneven splitting.**
* ✔️ Can be used on 1D, 2D, 3D, or higher dimensional arrays.
* ✔️ Supports custom axis splitting.



In [2]:
# Splitting 1D Array into Uneven Parts

arr = np.array([1, 2, 3, 4, 5, 6, 7])

# Split into 3 parts
result = np.array_split(arr, 3)

print(result)

# 👉 Since 7 elements cannot be divided equally into 3 parts, 
# it gives the first parts slightly larger.

[array([1, 2, 3]), array([4, 5]), array([6, 7])]


In [3]:
# Splitting 1D Array into Equal Parts

arr = np.array([10, 20, 30, 40, 50, 60])

# Split into 2 parts
result = np.array_split(arr, 2)

print(result)

[array([10, 20, 30]), array([40, 50, 60])]


In [4]:
#  Custom Axis Split on 2D Array

arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12]])
print(arr)
print(arr.shape)


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
(3, 4)


In [5]:
# Split along axis=0 (rows)
result = np.array_split(arr, 2, axis=0)
print(result)

for ele in result:
    print(ele, end = '\n\n')
    print(ele.shape, end = '\n\n')

[array([[1, 2, 3, 4],
       [5, 6, 7, 8]]), array([[ 9, 10, 11, 12]])]
[[1 2 3 4]
 [5 6 7 8]]

(2, 4)

[[ 9 10 11 12]]

(1, 4)



In [6]:
# Split along axis=1 (columns)
result = np.array_split(arr, 2, axis=1)
print(result)

for ele in result:
    print(ele, end = '\n\n')
    print(ele.shape, end = '\n\n')

[array([[ 1,  2],
       [ 5,  6],
       [ 9, 10]]), array([[ 3,  4],
       [ 7,  8],
       [11, 12]])]
[[ 1  2]
 [ 5  6]
 [ 9 10]]

(3, 2)

[[ 3  4]
 [ 7  8]
 [11 12]]

(3, 2)



In [7]:
arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8]])

# Split along axis=1 (columns)
result = np.array_split(arr, 3, axis=1)

for part in result:
    print(part)

[[1 2]
 [5 6]]
[[3]
 [7]]
[[4]
 [8]]


Visualizing Axis

* **axis=0 → split across rows (vertically)**
* **axis=1 → split across columns (horizontally)**

For this array:

```text
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
```

* `axis=0` splits like this: 👇

  ```
  Part 1:
  [[1 2 3 4]
   [5 6 7 8]]

  Part 2:
  [[ 9 10 11 12]]
  ```
* `axis=1` splits like this: 👇

  ```
  Part 1:
  [[1 2]
   [5 6]
   [9 10]]

  Part 2:
  [[3 4]
   [7 8]
   [11 12]]
  ```

**Difference from `numpy.split()`**

| Feature                | `numpy.array_split()` | `numpy.split()`        |
| ---------------------- | --------------------- | ---------------------- |
| Unequal split allowed? | ✔️ Yes                | ❌ No                   |
| Flexible?              | ✔️ Very flexible      | 🚫 Must divide equally |
| Error on uneven split? | ❌ Never               | ✔️ Yes                 |

---

**Key Takeaways:**

* Use **`array_split()` when array size may not divide evenly.**
* Works on **any axis** and any dimension.
* Safer than `split()` because it **never throws an error.**


In [8]:

# 3D array
arr = np.array([[[ 1,  2,  3],
                 [ 4,  5,  6],
                 [ 7,  8,  9],
                 [10, 11, 12]],

                [[13, 14, 15],
                 [16, 17, 18],
                 [19, 20, 21],
                 [22, 23, 24]]])

print(arr.shape)

(2, 4, 3)


In [9]:
# Split along axis=0 (depth / number of matrices)

result = np.array_split(arr, 2, axis=0)
for ele in result:
    print(ele, end = '\n\n')

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [10 11 12]]]

[[[13 14 15]
  [16 17 18]
  [19 20 21]
  [22 23 24]]]



In [10]:
# Split along axis=1 (rows in each matrix)

result = np.array_split(arr, 2, axis=1)
for ele in result:
    print(ele, end = '\n\n')

[[[ 1  2  3]
  [ 4  5  6]]

 [[13 14 15]
  [16 17 18]]]

[[[ 7  8  9]
  [10 11 12]]

 [[19 20 21]
  [22 23 24]]]



In [11]:
# Split along axis=1 (rows in each matrix)

result = np.array_split(arr, 3, axis=1)
for ele in result:
    print(ele, end = '\n\n')

[[[ 1  2  3]
  [ 4  5  6]]

 [[13 14 15]
  [16 17 18]]]

[[[ 7  8  9]]

 [[19 20 21]]]

[[[10 11 12]]

 [[22 23 24]]]



In [12]:
print(arr)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]
  [19 20 21]
  [22 23 24]]]


In [13]:
# Split along axis=2 (columns in each matrix)

result = np.array_split(arr, 2, axis=2)

for ele in result:
    print(ele, end='\n\n')

[[[ 1  2]
  [ 4  5]
  [ 7  8]
  [10 11]]

 [[13 14]
  [16 17]
  [19 20]
  [22 23]]]

[[[ 3]
  [ 6]
  [ 9]
  [12]]

 [[15]
  [18]
  [21]
  [24]]]



**3D array summary**

| Axis   | Meaning                     | Example Result                      |
| ------ | --------------------------- | ----------------------------------- |
| axis=0 | Splits the depth (matrices) | Divides the number of 2D layers     |
| axis=1 | Splits the rows             | Divides the rows within each matrix |
| axis=2 | Splits the columns          | Divides the columns within each row |


### 2. split()

`numpy.split()` is used to **split an array into multiple sub-arrays**.

🚩 **IMPORTANT DIFFERENCE:**
Unlike `array_split()`, **`split()` requires that the array must be divided into equal parts.**
If you try to split into unequal parts, it will raise an **error.**

---

**Syntax:**

```python
numpy.split(ary, indices_or_sections, axis=0)
```

**Parameters:**

* **ary**: The input array you want to split.
* **indices\_or\_sections**:

  * If it’s an integer → Number of equal-sized sub-arrays to split into.
  * If it’s a list → The split positions (indices) in the array.
* **axis**: The axis along which to split.
  Default is `axis=0` (split along rows).

---

**Key Rules:**

* ✔️ **When using an integer:**
  The array **must be divisible evenly** by this number.
* ✔️ **When using indices list:**
  You can split at custom positions.


In [14]:
# Splitting 1D Array into Equal Parts
arr = np.array([1, 2, 3, 4, 5, 6])

result = np.split(arr, 3)

for ele in result:
    print(ele)

[1 2]
[3 4]
[5 6]


In [15]:
result = np.split(arr, 3, axis=0)

for ele in result:
    print(ele)

[1 2]
[3 4]
[5 6]


In [16]:
# Uneven Split - Will Raise Error
   
arr = np.array([1, 2, 3, 4, 5, 6, 7])

try:
    np.split(arr, 3)
except Exception as e:
    print(f"Error: {e}")

# ❌ The array has 7 elements → not divisible by 3.

Error: array split does not result in an equal division


In [17]:
# Splitting 1D Array at Custom Positions
arr = np.array([1, 2, 3, 4, 5, 6, 7])

# Split at indices 2 and 5
result = np.split(arr, [2, 5])

for part in result:
    print(part)

[1 2]
[3 4 5]
[6 7]


✅ Custom split at **positions \[2, 5]**

* First part: elements 0 to 1
* Second part: elements 2 to 4
* Third part: elements 5 to end

In [18]:
# Splitting 2D Array 
arr = np.array([[1, 2],
                [3, 4],
                [5, 6],
                [7, 8]])

result = np.split(arr, 2, axis=0)

for ele in result:
    print(ele, end = '\n\n')

[[1 2]
 [3 4]]

[[5 6]
 [7 8]]



In [19]:
result = np.split(arr, 2, axis=1)

for ele in result:
    print(ele, end = '\n\n')

[[1]
 [3]
 [5]
 [7]]

[[2]
 [4]
 [6]
 [8]]



In [20]:
arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8]])

# Split into 2 equal parts along columns
result = np.split(arr, 2, axis=1)

for part in result:
    print(part, "\n")

[[1 2]
 [5 6]] 

[[3 4]
 [7 8]] 



In [21]:
# Splitting 3D Array

arr = np.arange(24).reshape(2, 4, 3)
print(arr)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]]


In [22]:
# Split into 2 equal parts along depth (axis=0)
result = np.split(arr, 2, axis=0)

for part in result:
    print(part, "\n")

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]] 

[[[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]] 



In [23]:
# Split into 2 equal parts along row (axis=1)
result = np.split(arr, 2, axis=1)

for part in result:
    print(part, "\n")

[[[ 0  1  2]
  [ 3  4  5]]

 [[12 13 14]
  [15 16 17]]] 

[[[ 6  7  8]
  [ 9 10 11]]

 [[18 19 20]
  [21 22 23]]] 



In [24]:
# Split into 2 equal parts along column (axis=2)

arr = np.arange(24).reshape(2, 3, 4)
print(arr)

result = np.split(arr, 2, axis=2)

for part in result:
    print(part, "\n")

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
[[[ 0  1]
  [ 4  5]
  [ 8  9]]

 [[12 13]
  [16 17]
  [20 21]]] 

[[[ 2  3]
  [ 6  7]
  [10 11]]

 [[14 15]
  [18 19]
  [22 23]]] 



**Summary Table: `split()` vs. `array_split()`**

| Feature                       | `numpy.split()`             | `numpy.array_split()` |
| ----------------------------- | --------------------------- | --------------------- |
| Uneven split allowed?         | ❌ No                        | ✔️ Yes                |
| Throws error on uneven split? | ✔️ Yes                      | ❌ No                  |
| Custom split positions?       | ✔️ Yes (using indices list) | ✔️ Yes                |
| Works on multi-dimensions?    | ✔️ Yes                      | ✔️ Yes                |

---

**When to Use:**

* ✔️ Use **`split()`** when you know the array **can be evenly divided.**
* ✔️ Use **`array_split()`** when you want to safely split arrays, even if the size is not perfectly divisible.

### 3. hsplit()

`numpy.hsplit()` is a **horizontal split function** that divides an array **along its columns** (i.e., along `axis=1`).

It is **a special case of `numpy.split()` where axis is always 1.**

---

**Syntax:**

```python
numpy.hsplit(array, sections)
```

**Parameters:**

* **array**: The input array to split.
* **sections**:

  * Integer → Number of equal parts.
  * List → Custom split positions.

---

**Key Rules:**

* ✔️ The array must be **at least 2D.**
* ✔️ Can only split **along columns (axis=1).**
* ✔️ If number of sections is given → must divide columns evenly.
* ✔️ Use custom indices list to split at specific positions.


In [25]:
arr = np.array([1, 2, 3, 4])

result = np.hsplit(arr, 2)

for ele in result:
    print(ele)

[1 2]
[3 4]


In [26]:
# Split into Equal Parts
arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8]])

# Split into 2 equal parts along columns
result = np.hsplit(arr, 2)

for part in result:
    print(part, "\n")

[[1 2]
 [5 6]] 

[[3 4]
 [7 8]] 



In [27]:
# Error on Uneven Split

arr = np.array([[1, 2, 3, 4, 5],
                [6, 7, 8, 9, 10]])

# Trying to split into 2 parts (5 columns is not divisible by 2)
try:
    result = np.hsplit(arr, 2)
except Exception as e:
    print(f"Error: {e}")

Error: array split does not result in an equal division


In [28]:
# Custom Split Positions
arr = np.array([[10, 20, 30, 40, 50],
                [60, 70, 80, 90, 100]])

# Split at indices 1 and 4
result = np.hsplit(arr, [1, 4])

for part in result:
    print(part, "\n")

[[10]
 [60]] 

[[20 30 40]
 [70 80 90]] 

[[ 50]
 [100]] 



✔️ Splits:

* Before column 1 → first part
* Between column 1 and 4 → second part
* After column 4 → third part

In [29]:
# 3D Array Horizontal Split
arr = np.arange(24).reshape(2, 4, 3)

print(arr)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]]


In [30]:
# Split into 3 parts along columns (axis=1)
result = np.hsplit(arr, 4)

for part in result:
    print(part, "\n")


[[[ 0  1  2]]

 [[12 13 14]]] 

[[[ 3  4  5]]

 [[15 16 17]]] 

[[[ 6  7  8]]

 [[18 19 20]]] 

[[[ 9 10 11]]

 [[21 22 23]]] 



**Visual Diagram**

Consider this array:

```text
[[ 1  2  3  4]
 [ 5  6  7  8]]
```

After `numpy.hsplit(arr, 2)`, you get:

```text
[[ 1  2]    and    [[ 3  4]
 [ 5  6]]           [ 7  8]]
```

👉 Horizontal split → cuts **vertically** through the array → separates columns.

---

**Summary**

| Feature       | Details                                     |
| ------------- | ------------------------------------------- |
| Split Axis    | axis=1 (columns)                            |
| Works On      | 2D, 3D, or higher                           |
| Supports      | Equal splits, Custom split indices          |
| Uneven Splits | ❌ Not allowed (use `array_split()` instead) |
| Equivalent To | `numpy.split(arr, sections, axis=1)`        |

---

**When to Use:**

* ✔️ When you want to **split an array along its columns.**
* ✔️ When you are sure **splits will be equal OR you can use custom indices.**


### 4. vsplit()

**`numpy.vsplit()`** is a **vertical split function** that splits an array **along its rows** (i.e., along `axis=0`).

It is a **special case of `numpy.split()` where the axis is always 0.**

---

**Syntax:**

```python
numpy.vsplit(array, sections)
```

**Parameters:**

* **array**: The input array you want to split.
* **sections**:

  * Integer → Number of equal parts.
  * List → Custom split positions.

---

**Key Rules:**

* ✔️ The array must be **at least 2D.**
* ✔️ It splits **along rows (axis=0).**
* ✔️ The array must be divisible evenly, unless you use custom split indices.
* ❌ If uneven splits are required → use `numpy.array_split()` instead.


In [31]:
arr = np.array([1, 2, 3, 4])

try:
    result = np.vsplit(arr, 2)
except Exception as e:
    print(f"Error: {e}")

Error: vsplit only works on arrays of 2 or more dimensions


In [32]:
#  Splitting 2D Array Vertically (Equal Parts)

arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8]])

# Split into 2 equal parts along rows
result = np.vsplit(arr, 2)

for part in result:
    print(part, "\n")

[[1 2 3 4]] 

[[5 6 7 8]] 



In [33]:
# Error on Uneven Split
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

# Trying to split into 2 parts → will cause error
try:
    result = np.vsplit(arr, 2)
except Exception as e:
    print(f"Error: {e}")
    
# ❌ Cannot split 3 rows into 2 equal parts.

Error: array split does not result in an equal division


In [34]:
# Custom Split Positions

arr = np.array([[10, 20, 30],
                [40, 50, 60],
                [70, 80, 90],
                [100, 110, 120]])

# Split at indices 1 and 3
result = np.vsplit(arr, [1, 3])

for part in result:
    print(part, "\n")

[[10 20 30]] 

[[40 50 60]
 [70 80 90]] 

[[100 110 120]] 



✔️ The split happens:

* Before row 1 → first part
* Between row 1 and 3 → second part
* After row 3 → third part

In [35]:
# Splitting 3D Array Vertically

arr = np.arange(24).reshape(4, 3, 2)
print(arr)

[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]

 [[12 13]
  [14 15]
  [16 17]]

 [[18 19]
  [20 21]
  [22 23]]]


In [36]:
# Split into 2 parts along rows
result = np.vsplit(arr, 2)

for part in result:
    print(part, "\n")

[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]] 

[[[12 13]
  [14 15]
  [16 17]]

 [[18 19]
  [20 21]
  [22 23]]] 



**Visual Diagram**

Consider this array:

```text
[[ 1  2  3  4]
 [ 5  6  7  8]]
```

When using `numpy.vsplit(arr, 2)`, you get:

```text
[[ 1  2  3  4]]   and   [[ 5  6  7  8]]
```

👉 **Vertical split → cuts horizontally through the array → separates rows.**

---

**Summary Table**

| Feature               | Description                          |
| --------------------- | ------------------------------------ |
| Splits along axis     | `axis=0` (rows)                      |
| Works with            | 2D, 3D, or higher arrays             |
| Supports              | Equal splits, Custom splits          |
| Uneven split allowed? | ❌ No                                 |
| Handles custom splits | ✔️ Yes                               |
| Equivalent to         | `numpy.split(arr, sections, axis=0)` |

---

**When to Use:**

* ✔️ When you need to **split an array along its rows.**
* ✔️ When you know the array can be evenly divided (unless using custom positions).


### 5. dsplit()

`numpy.dsplit()` is a **depth-wise splitting function** that splits arrays **along the third axis** → `axis=2` (columns in the depth dimension).

It is a **special case of `numpy.split()` where the split happens along `axis=2`.**

---

**Syntax:**

```python
numpy.dsplit(array, sections)
```

**Parameters:**

* **array**: The input array you want to split (must be at least 3D).
* **sections**:

  * Integer → Number of equal parts.
  * List → Custom split positions.

---

**Key Rules:**

* ✔️ The array must be **at least 3D.**
* ✔️ Splits **along axis=2 (depth).**
* ✔️ If using an integer, the split must result in **equal-sized sub-arrays.**
* ✔️ Uneven splits are **not allowed.** Use `numpy.array_split()` for that.

In [37]:
arr = np.array([1, 2, 3, 4])

try:
    np.dsplit(arr, 2)
except Exception as e:
    print(e)

dsplit only works on arrays of 3 or more dimensions


In [38]:
# Splitting 3D Array Equally

arr = np.array([[[1, 2, 3, 4],
                 [5, 6, 7, 8]],

                [[9, 10, 11, 12],
                 [13, 14, 15, 16]]])

print(arr) # Shape: (2, 2, 4)

[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 9 10 11 12]
  [13 14 15 16]]]


In [39]:
# Split into 2 equal parts along axis=2
result = np.dsplit(arr, 2)

for part in result:
    print(part, "\n")

[[[ 1  2]
  [ 5  6]]

 [[ 9 10]
  [13 14]]] 

[[[ 3  4]
  [ 7  8]]

 [[11 12]
  [15 16]]] 



In [40]:
# Error on Uneven Split
arr = np.array([[[1, 2, 3],
                 [4, 5, 6]],

                [[7, 8, 9],
                 [10, 11, 12]]])

# Trying to split into 2 parts → will cause error
try:
    result = np.dsplit(arr, 2)
except Exception as e:
    print(e)

array split does not result in an equal division


In [41]:
# Custom Split Positions

arr = np.array([[[10, 20, 30, 40],
                 [50, 60, 70, 80]],

                [[90, 100, 110, 120],
                 [130, 140, 150, 160]]])

# Split at depth positions 1 and 3
result = np.dsplit(arr, [1, 3])

for part in result:
    print(part, "\n")


[[[ 10]
  [ 50]]

 [[ 90]
  [130]]] 

[[[ 20  30]
  [ 60  70]]

 [[100 110]
  [140 150]]] 

[[[ 40]
  [ 80]]

 [[120]
  [160]]] 



✔️ The split happens:

* Before depth index 1 → first part
* Between indices 1 and 3 → second part
* After index 3 → third part

**Visual Diagram**

Imagine this 3D array:

```text
[[[ 1,  2,  3,  4],
  [ 5,  6,  7,  8]],

 [[ 9, 10, 11, 12],
  [13, 14, 15, 16]]]
```

Each "layer" like `[1, 2, 3, 4]` is along the **depth (axis=2).**

When using:

```python
np.dsplit(arr, 2)
```

The array splits **along the depth like this:**

```text
First Part:
[[[ 1  2]
  [ 5  6]]

 [[ 9 10]
  [13 14]]]

Second Part:
[[[ 3  4]
  [ 7  8]]

 [[11 12]
  [15 16]]]
```

👉 It **cuts the depth (3rd axis) into slices.**

---

**Summary Table**

| Feature               | Description                          |
| --------------------- | ------------------------------------ |
| Splits along axis     | `axis=2` (depth)                     |
| Works on              | 3D, 4D, or higher arrays             |
| Supports              | Equal splits, Custom splits          |
| Uneven split allowed? | ❌ No                                 |
| Handles custom splits | ✔️ Yes                               |
| Equivalent to         | `numpy.split(arr, sections, axis=2)` |

---

**When to Use:**

* ✔️ When you want to **split a 3D array along its depth.**
* ✔️ When you know the array can be evenly divided or when you use custom indices.


**comprehensive and consolidated summary** of all the NumPy **array splitting methods**: `split()`, `array_split()`, `hsplit()`, `vsplit()`, and `dsplit()`—including their **behavior, syntax, axis involved, examples, and comparisons.**

---

# 📘 Consolidated Summary: NumPy Splitting Methods

| Method             | Description                             | Works On | Axis Split | Equal Split Required? | Allows Custom Indices? | Unequal Split? |
| ------------------ | --------------------------------------- | -------- | ---------- | --------------------- | ---------------------- | -------------- |
| `np.split()`       | General-purpose split along any axis    | ≥1D      | Any axis   | ✅ Yes                 | ✅ Yes                  | ❌ No           |
| `np.array_split()` | More flexible general-purpose split     | ≥1D      | Any axis   | ❌ No                  | ✅ Yes                  | ✅ Yes          |
| `np.hsplit()`      | Horizontal split (splits columns)       | ≥2D      | axis=1     | ✅ Yes                 | ✅ Yes                  | ❌ No           |
| `np.vsplit()`      | Vertical split (splits rows)            | ≥2D      | axis=0     | ✅ Yes                 | ✅ Yes                  | ❌ No           |
| `np.dsplit()`      | Depth-wise split (splits depth/3rd dim) | ≥3D      | axis=2     | ✅ Yes                 | ✅ Yes                  | ❌ No           |

---

# 📌 Axis Meaning Cheat Sheet

| Axis   | Meaning                            | Used In                          |
| ------ | ---------------------------------- | -------------------------------- |
| axis=0 | Splits across rows (vertical)      | `vsplit`, `split`, `array_split` |
| axis=1 | Splits across columns (horizontal) | `hsplit`, `split`, `array_split` |
| axis=2 | Splits across depth (3rd dim)      | `dsplit`, `split`, `array_split` |

---

# 📘 Examples for Each Method

---

### ✅ 1. `np.split()`

```python
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6])
np.split(arr, 3)
```

📌 Output: `[[1 2], [3 4], [5 6]]`
❌ Throws error if uneven split is attempted.

---

### ✅ 2. `np.array_split()` – Safe Split

```python
arr = np.array([1, 2, 3, 4, 5, 6, 7])
np.array_split(arr, 3)
```

📌 Output: `[[1 2 3], [4 5], [6 7]]`
✅ Handles uneven splits gracefully.

---

### ✅ 3. `np.hsplit()` – Horizontal Split (Columns)

```python
arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8]])
np.hsplit(arr, 2)
```

📌 Output:

```
[[1 2]
 [5 6]]

[[3 4]
 [7 8]]
```

---

### ✅ 4. `np.vsplit()` – Vertical Split (Rows)

```python
arr = np.array([[1, 2, 3],
                [4, 5, 6]])
np.vsplit(arr, 2)
```

📌 Output:

```
[[1 2 3]]
[[4 5 6]]
```

---

### ✅ 5. `np.dsplit()` – Depth-wise Split (3rd Axis)

```python
arr = np.array([[[1, 2], [3, 4]],
                [[5, 6], [7, 8]]])
np.dsplit(arr, 2)
```

📌 Output:

```
[[[1], [3]],
 [[5], [7]]]

[[[2], [4]],
 [[6], [8]]]
```

---

# ✅ Quick Decision Guide

| Situation                          | Recommended Method |
| ---------------------------------- | ------------------ |
| Need to split evenly, any axis     | `np.split()`       |
| Need to split unevenly             | `np.array_split()` |
| Split 2D/3D horizontally (columns) | `np.hsplit()`      |
| Split 2D/3D vertically (rows)      | `np.vsplit()`      |
| Split 3D by depth slices           | `np.dsplit()`      |

---

# 🔚 Final Notes

* ✅ All splitting methods return **a list of NumPy arrays.**
* ✅ For **uneven splits**, always prefer `array_split()`.
* ❌ For **1D arrays**, do not use `hsplit()` or `vsplit()`—they require at least 2D.
* ❌ `dsplit()` requires at least a 3D array.

---



<center><b>Thanks</b></center>